time python SatDemo_0020.py birds.wav "The sound of chirping birds filled the air, creating a peaceful and harmonious ambiance."
time python SatDemo_0020.py chimes.wav  "A gentle tinkling sound filled the air, like the delicate chimes of a wind chime on a breezy day."
time python SatDemo_0020.py lullaby.wav "A gentle, enchanting melody filled the air, as if the plant itself was singing a sweet lullaby."
time python SatDemo_0020.py applause.wav "The sound of applause filled the gallery, echoing through the room and enveloping Emily in a wave of appreciation and support."
time python SatDemo_0020.py leaves.wav "The sound of rustling leaves and the playful chattering of monkeys filled the air, creating a lively and energetic atmosphere."