style_prompt_samples = [
    "Bubble Pop: The sudden burst of a soapy bubble, like a tiny drumbeat tickling your ear.",
    "Duck Quack: A loud, nasal honk as if the duck is laughing at its own joke.",
    "Jelly Wobble: A slow, floppy shake, like a bowl of giggling jelly on a trampoline.",
    "Snoring Teddy: The gentle rumble of a stuffed bear dreaming of honey and cuddles.",
    "Cuckoo Clock: A high-pitched 'cuckoo!' popping out, announcing the time in a cheeky tone.",
    "Slide Whistle: A slippery whoosh, like a bird swooping down and then straight back up.",
    "Slinky Tumble: A musical, playful descent as if stairs have become a xylophone.",
    "Clown Horn: A quick, honking beep, signaling a red-nosed, big-shoed arrival.",
    "Dripping Tap: Steady plip-plops, as if the faucet is trying to play a sneaky tune.",
    "Rubber Chicken Squeal: A ridiculous, high-pitched squawk of the funniest farmyard bird.",
    "Hiccup Surprise: A sudden, startled gulp of air, like someone's tummy telling a joke.",
    "Giggling Potion: Bubbly chuckles rising up, like a potion that can't stop laughing.",
    "Silly Robot: Whirrs, beeps, and bonks, the sound of a robot dancing with two left feet.",
    "Gum Pop: A sharp smack, as if your mouth is giving a mini round of applause.",
    "Mouse Giggle: A tiny, high-pitched chuckle, as if a little mouse just heard the best joke ever.",
    "Whoopee Cushion: A sudden, cheeky toot, signaling a sneaky prank in action.",
    "Magic Twinkle: Delicate chimes, like stars winking and giggling in the night sky.",
    "Elephant Trumpet: A big, bellowing call, like an elephant saying hello with a trombone trunk.",
    "Banana Peel Slip: A fast skidding sound, as if shoes are ice skating on butter.",
    "Munching Cookies: Loud, crispy crunches, like a cookie monster enjoying a snack-time feast.",
    "Sneezing Fairy: A delicate 'achoo', sprinkled with a hint of magic dust.",
    "Bouncing Pogo: Boing-boing-boing, the rhythm of jumping on an endless spring.",
    "Wind-Up Toy: A rhythmic tick-tock, like a little toy marching to a playful drumbeat.",
    "Squishy Hug: A soft, plush sound, like marshmallows getting a friendly squeeze.",
    "Gurgling Stream: Babbling giggles of water, as if the stream is sharing a secret joke.",
    "Kazoo Parade: A humming, buzzy melody, the anthem of a silly, one-man band.",
    "Tooting Flute: Sweet, airy notes, like birds whistling a goofy tune.",
    "Popping Popcorn: Tiny, rapid bursts, as if the kernels are having a ticklish dance party.",
    "Frog's Burp: A deep, rumbling sound, like a frog singing after a big meal.",
    "Slinky Spring: A twangy boing, the sound of a springy coil bouncing to and fro.",
    "Wobbling Plate: A low, humming wobble, as if dishes are having a dizzy dance-off.",
    "Creaky Door: A slow, squeaky groan, like a door stretching after a long nap.",
    "Chirping Crickets: High-pitched trills, as if the night's insects are playing tiny violins.",
    "Tickling Feathers: Soft, fluttery whispers, like feathers giggling in a gentle breeze.",
    "Jingling Bells: Bright, tinkling chimes, as if little fairies are having a bell party.",
    "Rattling Maracas: A shakey, rhythmic sound, like a pair of maracas having a lively chat."
]