style_prompt_samples = [
    "Overwhelming dread from a distant echoing scream",
    "A jolt of panic from a sudden loud bang",
    "A rush of nostalgia from an old familiar tune",
    "Stifling unease from the creaking of a floorboard",
    "Heart-racing anticipation from a ticking clock",
    "Gut-wrenching sorrow from a mournful violin",
    "Overpowering joy from a child's gleeful laughter",
    "Deep solitude from the haunting call of a loon",
    "Eerie discomfort from a whisper in the dark",
    "Bittersweet longing from an old lullaby",
    "Unsettling paranoia from footsteps behind you",
    "Stinging regret from a sad piano melody",
    "Soothing serenity from the sound of gentle rain",
    "Pulsating excitement from a roaring crowd",
    "Deafening shock from an unexpected explosion",
    "Warm comfort from the crackling of a fireplace",
    "Bone-chilling terror from a wolf's midnight howl",
    "Wistful melancholy from the tolling of a distant bell",
    "Intense focus from the rhythm of a metronome",
    "Quiet introspection from the hum of the wilderness",
    "Stomach-churning anxiety from a phone's persistent ring",
    "Crippling fear from the growl of an unseen beast",
    "Fluttering hope from a bird's song at dawn",
    "Fleeting annoyance from the buzz of a mosquito",
    "Deep-rooted yearning from a train's distant whistle",
    "Heartfelt elation from a loved one's voice",
    "Chilling foreboding from the hiss of a snake",
    "Relaxing calm from the babble of a brook",
    "Exhilarating adrenaline from a race car's engine roar",
    "Overbearing grief from the sound of taps played at a funeral",
    "Nervous apprehension from an oscillating fan's inconsistent whir",
    "Sudden realization from a resounding gong",
    "Comforting nostalgia from the chime of an ice cream truck",
    "Searing jealousy from whispered secrets",
    "Unbearable tension from the drawn-out notes of a suspenseful chord",
    "Uncontrollable joy from the pop of a champagne cork"
]
