

positive_prompt_samples = [
    "Dancing Bananas: A group of bananas, each with smiling faces, dancing in a conga line wearing sunglasses and beach hats.",
    "Penguin's Pool Party: Penguins wearing swimsuits, sunbathing on towels, and sipping on juice boxes by a pool filled with rubber duckies.",
    # "Alien's Day at School: A friendly green alien struggling to carry an oversized school backpack, while being surrounded by curious school kids.",
    # "The Roller-skating Rabbit: A fluffy bunny on roller-skates, zooming past a group of astonished tortoises who are moving at a snail's pace.",
    # "Fish's Underwater Birthday: Colorful fish wearing party hats, blowing party horns, and floating around a seaweed-decorated birthday cake.",
    # "Giraffe's Bad Hair Day: A giraffe looking shocked at its frizzy, rainbow-colored mane in a mirror, while a cheeky monkey holds a hair dryer.",
    # "Elephant's Ice Cream Oops: A clumsy elephant dropping a mountain of ice cream scoops from its cone, while ants cheer in anticipation below.",
    # "Dragon's BBQ Mishap: A dragon accidentally setting its marshmallow on fire while trying to roast it, with a group of giggling fairies holding fire extinguishers.",
    # "Unicorn's Paint Day: A unicorn with a paintbrush in its tail, accidentally splattering rainbow paint everywhere and creating abstract masterpieces.",
    # "Hippo's Ballet Recital: A graceful hippopotamus in a tutu, pirouetting on stage while other animals applaud enthusiastically.",
    # "Bear's Pillow Fort: A bear snug inside a grand pillow fort, reading a storybook by flashlight, surrounded by stuffed animal friends.",
    # "Snail's Rocket Ride: A snail with wide-eyed excitement, strapping onto a tiny rocket, ready to zoom around at unbelievable speeds.",
    # "Lion's Vegetable Quest: A lion with a shopping list, looking puzzled in a vegetable market, trying to figure out what broccoli is.",
    # "Squirrel's Nutty Band: Squirrels playing instruments made out of acorns and leaves, holding a concert for a crowd of woodland creatures.",
    # "Mouse's Cheese Moon: A mouse astronaut planting a flag on a moon made entirely of cheese, while aliens scratch their heads in confusion.",
    # "Octopus's Bake-Off: An octopus wearing a chef's hat, juggling multiple baking tasks with its tentacles, resulting in a flurry of flour and flying pastries.",
    # "Zebra's Stripe Wash: A zebra at a car wash, getting its stripes cleaned, and coming out with fun, colorful patterns instead of the usual black and white.",
    # "Owl's Nighttime Disco: Owls wearing glittery outfits, dancing under a disco ball that's illuminated by fireflies.",
    # "Pig's Mud Spa Day: Pigs lounging and getting facials in a luxurious mud spa, with cucumbers on their eyes and towels wrapped around.",
    # "Kangaroo's Jump Rope Challenge: A kangaroo expertly hopping over a jump rope held by two cheering koalas.",
    # "Crocodile's Toothbrush Dilemma: A crocodile trying to decide among a vast array of oversized toothbrushes to clean its many teeth.",
    # "Fox's Magic Show: A fox pulling out surprised rabbits from a hat, while the rabbits hold tiny flags saying, 'Not again!'.",
    # "Chicken's Sky Dive: Chickens parachuting from the sky, with one holding onto an egg, trying not to drop it.",
    # "Seal's Musical Performance: A seal balancing a ball on its nose, which is actually a disco globe, while other sea animals dance around.",
    # "Raccoon's Treasure Hunt: Raccoons dressed as pirates, searching for treasures in a playground sandbox.",
    # "Bee's Honey Café: Bees running a tiny café, serving honey lattes and pollen pastries to other bugs.",
    # "Turtle's Skateboard Park: Turtles on skateboards, attempting to do slow-motion tricks while snails cheer them on.",
    # "Sheep's Woolly Fashion Show: Sheep walking on a runway, showcasing stylish woolly sweaters and hats.",
    # "Goose's Fancy Tea Party: Geese wearing elegant hats, sipping tea from patterned cups on a lakeside.",
    # "Jellyfish's Electric Light Festival: Glowing jellyfish floating in the ocean depths, creating a mesmerizing light show.",
    # "Frog's Rainy Concert: Frogs holding a concert on lily pads, using raindrops as their rhythmic beats.",
    # "Cheetah's Slow-Mo Race: A cheetah racing against tortoises, but humorously moving in super slow motion.",
    # "Gorilla's Jungle Gym Workout: Gorillas flexing their muscles and working out at a jungle gym made of vines and trees.",
    # "Parrot's Karaoke Night: A parrot singing enthusiastically into a microphone, while other birds tweet their approval.",
    # "Shark's Dentist Visit: A nervous shark on the dentist's chair, while a small fish in a white coat checks its teeth.",
    # "Cat's Dreamland Adventure: Cats riding on fluffy cloud boats, fishing for stars in a sky filled with milk rivers."
]
