style_prompt_samples = [
    "Bluesy lamentations in the style of B.B. King, Muddy Waters, and Robert Johnson",
    "Soulful rhythm and grooves in the style of Aretha Franklin, Marvin Gaye, and Otis Redding",
    "Fiery flamenco guitar riffs in the style of Paco de Lucía, Tomatito, and Vicente Amigo",
    "Psychedelic rock jams in the style of Jimi Hendrix, Pink Floyd, and The Grateful Dead",
    "Pumping techno beats in the style of Carl Cox, Richie Hawtin, and Jeff Mills",
    "Lyrical hip-hop verses in the style of Tupac Shakur, Notorious B.I.G., and Nas",
    "Sultry jazz improvisations in the style of Miles Davis, John Coltrane, and Ella Fitzgerald",
    "Heavy metal shredding in the style of Metallica, Iron Maiden, and Black Sabbath",
    "Melodious pop hooks in the style of Madonna, Michael Jackson, and Whitney Houston",
    "Reggae rhythms and vibes in the style of Bob Marley, Peter Tosh, and Burning Spear",
    "Country ballads and tales in the style of Johnny Cash, Dolly Parton, and Willie Nelson",
    "Classical symphonies in the style of Ludwig van Beethoven, Wolfgang Amadeus Mozart, and Johann Sebastian Bach",
    "Punky rebellious anthems in the style of The Clash, Ramones, and Sex Pistols",
    "Funky basslines and breaks in the style of James Brown, George Clinton, and Bootsy Collins",
    "Latin salsa rhythms in the style of Celia Cruz, Hector Lavoe, and Rubén Blades",
    "Smooth R&B harmonies in the style of Boyz II Men, Mariah Carey, and R. Kelly",
    "Energetic ska beats in the style of The Specials, Madness, and Toots and the Maytals",
    "Gritty grunge sounds in the style of Nirvana, Pearl Jam, and Soundgarden",
    "Rapid-fire rap bars in the style of Eminem, Busta Rhymes, and Tech N9ne",
    "Enchanting opera arias in the style of Luciano Pavarotti, Maria Callas, and Plácido Domingo",
    "Electronic trance melodies in the style of Armin van Buuren, Tiesto, and Paul van Dyk",
    "Soothing folk tales in the style of Bob Dylan, Joni Mitchell, and Simon & Garfunkel",
    "Catchy disco grooves in the style of Bee Gees, Donna Summer, and Chic",
    "Raw rock 'n' roll in the style of Elvis Presley, Chuck Berry, and Little Richard",
    "Bouncy afrobeat rhythms in the style of Fela Kuti, Tony Allen, and Seun Kuti",
    "Ambient soundscapes in the style of Brian Eno, Aphex Twin, and Moby",
    "Rootsy bluegrass picking in the style of Bill Monroe, Earl Scruggs, and Alison Krauss",
    "Killer drum and bass in the style of Goldie, Roni Size, and Andy C",
    "Melancholic indie tunes in the style of The Smiths, Arcade Fire, and The National",
    "Upbeat calypso rhythms in the style of Harry Belafonte, Lord Kitchener, and Mighty Sparrow",
    "Swinging big band numbers in the style of Glenn Miller, Duke Ellington, and Count Basie",
    "Groovy house tracks in the style of Frankie Knuckles, Larry Heard, and Marshall Jefferson",
    "Electrifying gospel choruses in the style of Mahalia Jackson, Kirk Franklin, and The Clark Sisters",
    "Harmonious barbershop quartets in the style of The Buffalo Bills, Gas House Gang, and The New Tradition"  
]
