
questions_dict = {
    "Do you have any siblings?": ["Yes", "No"],
    "Which is your favorite color?": ["Red", "Blue", "Green", "Yellow", "Purple", "Pink", "Orange", "Other"],
    "What type of pet would you like to have?": ["Dog", "Cat", "Fish", "Bird", "Hamster", "Rabbit", "None", "Other"],
    "Which fruit do you like the most?": ["Apple", "Banana", "Grapes", "Orange", "Strawberry", "Other"],
    "Which is your favorite season?": ["Spring", "Summer", "Fall", "Winter"],
    "Do you like to read?": ["Yes", "No", "Sometimes"],
    "Which is your favorite meal?": ["Breakfast", "Lunch", "Dinner", "Snack"],
    "Do you prefer indoor or outdoor play?": ["Indoor", "Outdoor", "Both"],
    "Do you have a favorite toy?": ["Yes", "No"],
    "What's your favorite subject in school?": ["Math", "Reading", "Science", "Art", "Music", "Physical Education", "Not in school", "Other"],
    "Do you like to draw?": ["Yes", "No", "Sometimes"],
    "How do you feel about bedtime?": ["I like it", "I don't like it", "It's okay"],
    "What's your favorite sport?": ["Soccer", "Basketball", "Baseball", "Swimming", "Dance", "None", "Other"],
    "Do you like to help in the kitchen?": ["Yes", "No", "Sometimes"],
    "Do you have a best friend?": ["Yes", "No"],
    "What's your favorite kind of music?": ["Pop", "Classical", "Rock", "Children's songs", "Don't know", "Other"],
    "Do you like to watch TV or movies?": ["Yes", "No", "Sometimes"],
    "What's your favorite animal?": ["Lion", "Elephant", "Dolphin", "Giraffe", "Other"],
    "Do you like to go to the park?": ["Yes", "No", "Sometimes"],
    "Do you enjoy family trips?": ["Yes", "No", "Sometimes"],
    "Do you have a favorite game?": ["Board game", "Video game", "Hide and seek", "Tag", "Other"],
    "Do you have chores at home?": ["Yes", "No"],
    "Do you like to dance?": ["Yes", "No", "Sometimes"],
    "Do you enjoy story time?": ["Yes", "No", "Sometimes"],
    "How do you feel about school?": ["I love it", "It's okay", "I don't like it", "Not in school"],
    "Do you like ice cream?": ["Yes", "No"],
    "What's your favorite holiday?": ["Christmas", "Halloween", "Easter", "Birthday", "Other"],
    "Do you like to visit the library?": ["Yes", "No", "Sometimes"],
    "Do you have a favorite teacher?": ["Yes", "No", "Not in school"],
    "Do you like puzzles?": ["Yes", "No", "Sometimes"],
    "Do you have a favorite bedtime story?": ["Yes", "No", "Don't know"],
    "Do you like to sing?": ["Yes", "No", "Sometimes"],
    "Do you have a favorite cartoon or character?": ["Yes", "No", "Don't know"]
}



parent_question_list = [
    "What's your child's favorite color?",
    "Does your child have any siblings?",
    "What's your child's favorite toy to play with?",
    "Which cartoons or TV shows does your child like to watch?",
    "Does your child have a pet? If so, what kind?",
    "What's your child's favorite snack to eat?",
    "Does your child like to draw or color?",
    "What's the most fun game your child has ever played?",
    "What does your child like to do outside?",
    "Where did you take your child on your last vacation?",
    "Does your child like to read or have stories read to them?",
    "What's your child's favorite bedtime story?",
    "Has your child ever been to a theme park?",
    "What's your child's favorite ice cream flavor?",
    "Does your child have a best friend?",
    "What's your child's favorite song to sing?",
    "Can your child play any musical instruments?",
    "Does your child like to dance?",
    "Has your child ever seen a rainbow?",
    "What's your child's favorite animal at the zoo?",
    "Does your child play any sports or take any classes?",
    "What makes your child really happy?",
    "Does your child prefer the beach or the mountains?",
    "What's the funniest joke your child knows?",
    "Does your child like puzzles or board games?",
    "What does your child want to be when they grow up?",
    "Does your child have any special talents or tricks?",
    "What's the coolest place your child has ever been to?",
    "Does your child prefer dinosaurs or space?",
    "What's your child's favorite season? winter, spring, summer, or fall?",
    "Has your child ever built a snowman?",
    "Does your child know how to ride a bicycle?",
    "What's your child's favorite fruit?",
    "Does your child like to go to the movies or watch at home?",
    "What does your child usually have for breakfast?",
    "Do you have any special traditions with your child?"
]

parent_question_list2 = [
    "What's their name?",
    "How old are they?",
    "Do they have any brothers or sisters?",
    "Do they have any pets?",
    "What's their favorite color?",
    "Do they go to school?",
    "What grade are they in?",
    "Do they have a favorite hobby?",
    "Do they play any sports?",
    "Do they play a musical instrument?",
    "Who's their best friend?",
    "What's their favorite movie?",
    "What's their favorite toy?",
    "What's their favorite book?",
    "What's their favorite game?",
    "What's their favorite food?",
    "What's their favorite snack?",
    "What's their favorite ice cream flavor?",
    "Where's their favorite place to go?",
    "What's their favorite holiday?",
    "What's their favorite season?",
    "Do they have a favorite outfit?",
    "What's their favorite song?",
    "What's their favorite animal?",
    "Who's their favorite superhero?",
    "What time do they go to bed?",
    "What time do they usually wake up?",
    "What's their hair color?",
    "What's their eye color?",
    "Who's their favorite teacher?",
    "What's their favorite subject in school?",
    "What's their favorite playground equipment?",
    "What's their favorite TV show?",
    "What's their favorite activity?",
    "What's their favorite fruit?",
    "What's their favorite vegetable?"
]

child_question_list = [
    "What's your favorite color?",
    "Do you have any brothers or sisters?",
    "What's your favorite toy to play with?",
    "Which cartoons or TV shows do you like to watch?",
    "Do you have a pet? If so, what kind?",
    "What's your favorite snack to eat?",
    "Do you like to draw or color?",
    "What's the most fun game you've ever played?",
    "What do you like to do outside?",
    "Where did you go on your last vacation?",
    "Do you like to read or have stories read to you?",
    "What's your favorite bedtime story?",
    "Have you ever been to a theme park?",
    "What's your favorite ice cream flavor?",
    "Do you have a best friend?",
    "What's your favorite song to sing?",
    "Can you play any musical instruments?",
    "Do you like to dance?",
    "Have you ever seen a rainbow?",
    "What's your favorite animal at the zoo?",
    "Do you play any sports or take any classes?",
    "What makes you really happy?",
    "Do you like the beach or the mountains?",
    "What's the funniest joke you know?",
    "Do you like puzzles or board games?",
    "What do you want to be when you grow up?",
    "Do you have any special talents or tricks?",
    "What's the coolest place you've ever been to?",
    "Do you like dinosaurs or space more?",
    "What's your favorite season: winter, spring, summer, or fall?",
    "Have you ever built a snowman?",
    "Do you know how to ride a bicycle?",
    "What's your favorite fruit?",
    "Do you like to go to the movies or watch at home?",
    "What do you usually have for breakfast?",
    "Do you have any special traditions with your family?"
]
