# Story element brainstorm

morals_list = [
    "Treat others as you want to be treated.",
    "It's okay to make mistakes, but it's important to apologize.",
    "Sharing with others makes playtime more fun.",
    "Telling the truth builds trust with others.",
    "Being patient means waiting your turn without complaining.",
    "Every person is unique and special in their own way.",
    "Taking care of your belongings shows responsibility.",
    "Listening to others shows you care about their feelings.",
    "It's okay to say no when you feel uncomfortable.",
    "Hard work and effort often lead to great rewards.",
    "Always say please and thank you to show appreciation.",
    "Helping others can make you feel good too.",
    "Judging others by their looks isn't fair.",
    "Taking a deep breath can help you calm down.",
    "Respecting nature means not littering and harming animals.",
    "It's more fun to play when everyone plays by the rules.",
    "Everyone has feelings, even if they don't show them.",
    "Being kind is more important than being right.",
    "Even when it's hard, always try your best.",
    "Reading and learning can take you on amazing adventures.",
    "Making fun of others can hurt their feelings.",
    "It's okay to ask for help when you need it.",
    "Taking breaks is okay when you feel overwhelmed.",
    "Washing your hands keeps germs away.",
    "Being a good friend means being supportive and understanding.",
    "You should never take something that doesn't belong to you.",
    "Including everyone in games and activities is the right thing to do.",
    "It's okay to have different feelings, and it's okay to talk about them.",
    "Keeping promises is a way to show you're trustworthy.",
    "Always look both ways before crossing the street.",
    "Being polite and using kind words makes others happy.",
    "Even if you're small, your actions can make a big difference.",
    "Accepting that people have different opinions is part of growing up.",
    "Being curious and asking questions helps you learn.",
    "Practice and persistence can help you get better at something.",
    "Taking care of pets teaches you responsibility and compassion."
]

event_list = [
    "First day of preschool",
    "Making a best friend",
    "Losing a first tooth",
    "Learning to tie shoelaces",
    "Riding a bike without training wheels",
    "First school field trip",
    "Mastering reading a book independently",
    "Getting a first report card",
    "Participating in a school play or performance",
    "Joining a team sport or extracurricular",
    "Attending a friend's birthday party",
    "Learning to swim",
    "First sleepover",
    "Acquiring a new sibling",
    "Mastering basic arithmetic",
    "First school project",
    "Experiencing a first crush",
    "First visit to a museum or cultural site",
    # "Achieving a personal goal",
    "Learning a musical instrument",
    "First time away from parents overnight",
    "Dealing with a first disappointment or failure",
    "Receiving a special award or recognition",
    "Discovering a personal hobby or passion",
    "First time experiencing the loss of a pet",
    "Learning about cultural or family traditions",
    "Beginning of understanding morality",
    "First chapter book completion",
    "Participating in a school contest or fair",
    "Making a significant contribution to family",
    "Learning about and experiencing different seasons",
    "First experience with responsibility (e.g., pet care)",
    "Understanding the value of money",
    "Gaining a new responsibility at home",
    "First camping trip or outdoor adventure",
    "Formulating personal beliefs and opinions"
]

trouble_list = [
    "Struggling to tie shoelaces",
    "Losing a favorite toy",
    "Having nightmares",
    "Being bullied at school or playground",
    "Difficulty making friends",
    "Resisting bedtime",
    "Not liking the food on their plate",
    "Difficulty understanding homework",
    "Being too short to reach things",
    "Fear of monsters or the dark",
    "Struggling to read",
    "Feeling left out",
    "Getting injured while playing",
    "Fear of doctors or injections",
    "Not being able to express feelings",
    "Being scolded by teachers or parents",
    "Feeling jealous of siblings",
    "Dealing with changes, like moving homes",
    "Struggling with the concept of sharing",
    "Losing a tooth and fearing the pain",
    "Fear of swimming or water",
    "Not being invited to a birthday party",
    "Not understanding why they can’t have certain things",
    "Not being allowed to watch a particular TV show",
    "Struggling to ride a bicycle",
    "Dealing with the death of a pet",
    "Having to adjust to a new sibling",
    "Feeling embarrassed over accidents (like bedwetting)",
    "Fear of loud noises or crowds",
    "Struggling with transitions (e.g., from playtime to homework)",
    "Feeling pressured to win or be the best in a game/sport",
    "Not being allowed to play outside",
    "Feeling overwhelmed by too many activities",
    "Missing a parent who travels or works long hours",
    "Difficulty understanding rules",
    "Having to finish vegetables before dessert"
]

lesson_list = [
    "Alphabet recognition",
    "Basic counting (1-100)",
    "Simple addition and subtraction",
    "Shapes and their names",
    "Colors and their names",
    "Days of the week",
    "Months of the year",
    "Basic reading skills",
    "Writing their own name",
    "Listening to and following instructions",
    "Basic personal hygiene (e.g., brushing teeth)",
    "Tying shoe laces",
    "Manners (please, thank you, etc.)",
    "Safety rules (e.g., not talking to strangers)",
    "Basic understanding of time (morning, afternoon, night)",
    "Recognizing basic money denominations",
    "Basic problem-solving skills",
    "Understanding emotions and feelings",
    "Basic knowledge of the five senses",
    "Recognizing family members’ names and roles",
    "Basic classification skills (e.g., animals vs. plants)",
    "Simple rhyming words",
    "Basic bodily autonomy and personal boundaries",
    "Sharing with others",
    "Taking turns",
    "Building basic motor skills (e.g., hopping, skipping)",
    "Understanding the concept of 'before' and 'after'",
    "Recalling and retelling simple stories",
    "Understanding differences (e.g., big vs. small, tall vs. short)",
    "Understanding seasons and basic weather patterns",
    "Basic cultural and holiday awareness",
    "Simple chores and responsibilities (e.g., cleaning up toys)",
    "Recognizing basic patterns and sequences",
    "Asking questions to gain understanding",
    "Expressing oneself verbally",
    "Basic knowledge of their physical address and phone number",
    "Introduction to basic technology (e.g., how to use a tablet)",
    "Recognizing and understanding the value of friendship",
    "Understanding the importance of honesty",
    "Awareness of basic environmental concepts (e.g., recycling)"
]

profession_list = [
    "Astronaut",
    "Doctor",
    "Firefighter",
    "Teacher",
    "Veterinarian",
    "Police Officer",
    "Chef",
    "Dentist",
    "Farmer",
    "Pilot",
    "Dancer",
    "Zookeeper",
    "Engineer",
    "Nurse",
    "Scientist",
    "Mail Carrier",
    "Bus Driver",
    "Soldier",
    "Musician",
    "Librarian",
    "Baker",
    "Athlete",
    "Artist",
    "Actor",
    "Magician",
    "Construction Worker",
    "Hairdresser",
    "Photographer",
    "Marine Biologist",
    "Journalist",
    "Mechanic",
    "Astronomer",
    "Architect",
    "Fashion Designer",
    "Fisherman",
    "Plumber"
]

soundy_things_list = [
    "Toy train",
    "Bicycle bell",
    "Squeaky toy",
    "School bus brakes",
    "Jump rope hitting the ground",
    "Crayons or colored pencils on paper",
    "Electronic handheld game sounds",
    "Lunchbox latch snapping",
    "Popping bubble wrap",
    "Watercolor paintbrush swishing in a cup",
    "Slinky going down stairs",
    "Toy cash register",
    "Building blocks tumbling",
    "Pencil sharpener",
    "Rubber ball bouncing",
    "Plastic action figure articulations",
    "Flipping storybook pages",
    "Push-toy with popping balls",
    "Toy phone ringing",
    "Sand toys digging in the sandbox",
    "Piano or keyboard toy",
    "Toy drum",
    "Zipper of a backpack",
    "Velcro shoe straps",
    "Wind-up toy moving",
    "Jack-in-the-box popping",
    "Chalk drawing on sidewalk",
    "Toy car engine",
    "Whistle",
    "Blowing bubbles wand",
    "Toy kitchen appliances",
    "Electronic toy animal sounds",
    "Yoyo going up and down",
    "Water gun squirting",
    "Popping balloons",
    "Children's music box playing"
]

feelings_list = [
    ("Happiness","Like a warm, sunny day where everything feels light and you want to skip and jump around."),
    ("Sadness","A heavy cloud in your chest, making everything seem gray, like a rainy day where you can't play outside."),
    ("Frustration","The feeling of trying to fit a square block into a round hole over and over again."),
    ("Excitement","The bubbly fizz in a soda can, waiting to burst out when you hear fun news or see a new toy."),
    ("Loneliness","Standing in a big open field all by yourself, wishing for a friend to join you."),
    ("Curiosity","The tug in your tummy when you see a wrapped gift and you just have to know what's inside."),
    ("Fear","A dark, shadowy figure at the edge of your room, making your heart beat fast and wanting to hide under the covers."),
    ("Bravery","Standing tall like a superhero, even when your knees are shaking, ready to face the challenge."),
    ("Jealousy","Watching someone else with the toy you've always wanted, feeling a sour taste in your mouth."),
    ("Love","A big, warm hug from your favorite person, making you feel safe and treasured."),
    ("Confusion","Like trying to read a book upside down and backwards, not understanding what's happening."),
    ("Pride","Standing tall with a big grin, feeling like a balloon expanding with air, after achieving something new."),
    ("Embarrassment","A hot, red face, feeling like everyone's looking at you after you slipped on a banana peel."),
    ("Surprise","A sudden pop, like a jack-in-the-box jumping out when you least expect it."),
    ("Guilt","The heavy stone in your stomach after you've taken a cookie without asking."),
    ("Gratitude","The soft, glowing feeling when someone helps you tie your shoes or shares their lunch."),
    ("Hope","Watching the tiniest sprout in a pot, believing it will grow into a big, beautiful plant."),
    ("Disappointment","Waiting for ice cream and then dropping it in the sand, a heavy sigh in your heart."),
    ("Determination","Like a little train chugging up a steep hill, repeating 'I think I can, I think I can'."),
    ("Boredom","The long, slow tick of a clock, waiting for something fun to happen."),
    ("Relaxation","Lying on a soft cloud, drifting slowly, feeling light and free."),
    ("Anger","A volcano ready to erupt, hot and fiery, wanting to stomp and shout."),
    ("Compassion","Seeing a hurt bird and wanting to wrap it in a soft blanket, making it better."),
    ("Wonder","Gazing at a sky full of twinkling stars, feeling small yet connected to the universe."),
    ("Anticipation","The night before your birthday, barely able to sleep, thinking about the cake and presents."),
    ("Joy","Bursting into laughter, feeling like you're soaring on a swing, higher and higher."),
    ("Regret","Wishing you could rewind time, like pressing a backward button on a toy, to fix a mistake."),
    ("Patience","Watching paint dry or waiting in line, taking slow, deep breaths and staying calm."),
    ("Confidence","Wearing a shiny crown, believing you can do anything, like the king or queen of your own story."),
    ("Shyness","Hiding behind a big book, peeking out just a little, hoping no one notices."),
    ("Acceptance","Embracing a rainy day, jumping in puddles, knowing you can't change it and deciding to have fun anyway."),
    ("Exhaustion","Feeling like a deflated balloon, needing a cozy bed and a soft lullaby."),
    ("Amazement","Watching a magician pull a rabbit out of a hat, eyes wide, mouth open in awe."),
    ("Trust","Closing your eyes and falling back, knowing your friend will catch you, feeling safe and cared for."),
    ("Adventure","Ready with a backpack and a map, heart racing, eager to explore new mysteries and treasures."),
    ("Contentment","Snuggled in a blanket fort, with a good story and a soft light, feeling complete and at peace."),    
]

parable_list = [
    ("The Lost Toy", 
    "Once in a small town, a little boy named Max lost his favorite toy truck. He searched everywhere but couldn't find it. Instead of giving up, Max started helping others find their lost things. One day, while helping a friend, he found his toy truck. Helping others had led him to his own happiness."),

    ("The Generous Tree", 
    "There was a big, old tree in a forest. Kids loved to play under its shade. As the tree aged, it couldn't provide fruits or flowers, but it still gave shade and shelter. The tree taught everyone that even if you have little, you can always give kindness."),

    ("The Stubborn Rock", 
    "In the middle of a stream, there was a stubborn rock that wouldn't move. Over time, the gentle water shaped and smoothed the rock, showing that patience and persistence can change the hardest of things."),

    ("The Hungry Wolf", 
    "A wolf, hungry for days, found a lamb trapped. Instead of eating it, he set it free. Later, the lamb brought its flock to the wolf, and they lived in harmony. Kindness returns with more kindness."),

    ("The Colorful Birds", 
    "Different birds - red, blue, green, and yellow - lived in separate trees. One day, a storm mixed them all. When they sang together, the forest echoed with the most beautiful song ever. Unity is strength."),

    ("The Silent Flute", 
    "A flute, neglected and dusty, sat on a shelf. When a girl played it, the melodies were mesmerizing. Everyone has hidden talents waiting to be discovered."),

    ("The Dancing Leaves", 
    "Leaves on a tree laughed at fallen leaves. But come autumn, they too fell and danced in the wind. Every stage of life is beautiful in its own way."),

    ("The Lazy Sunflower", 
    "A sunflower didn't want to follow the sun. It soon wilted and lost its brightness. But when it started following the sun again, it bloomed. Growth requires effort."),

    ("The Brave Kitten", 
    "A small kitten, unlike her friends, wasn't afraid of the water. One day, she saved her siblings from a flood. Courage isn't about size, but heart."),

    ("The Echoing Mountain", 
    "A boy shouted insults at a mountain, and the insults returned as echoes. When he praised it, loving words echoed back. The world reflects what you give it."),

    ("The Giving Farmer", 
    "A farmer had three fields. He planted one, left one fallow, and gave one's produce to the needy. Years later, the shared field was the most fertile. Generosity enriches."),

    ("The Curious Star", 
    "A star descended to Earth out of curiosity and became a firefly. She lit up nights and made friends. Curiosity leads to wonderful adventures."),

    ("The Ocean's Whisper", 
    "A child asked the ocean about its vastness. The ocean whispered, 'One drop at a time.' Every big thing starts small."),

    ("The Wise Owl", 
    "An owl watched animals argue over who's the best. It said, 'Every creature has a unique role. Everyone is important.'"),

    ("The Shy Rainbow", 
    "A rainbow was shy and hid behind clouds. But when it showed itself, the world celebrated its colors. Embrace who you are."),

    ("The Two Moons", 
    "A lake saw two moons – one in the sky, one reflected. It realized the beauty it held within. External beauty is a reflection of the inside."),

    ("The Dreaming Stone", 
    "A stone dreamed of the sky. Birds carried it upwards. Although it fell back, it had touched the sky. Dreams are worth chasing."),

    ("The Joyful River", 
    "A river sang along its journey, making every creature cheerful. It showed joy is contagious."),

    ("The Tired Cloud", 
    "A cloud tired of floating rained down. When it rose again, it was lighter and happier. It's okay to let out feelings."),

    ("The Lonely Snowflake", 
    "A snowflake felt lonely, but soon it was joined by others, turning the land into a winter wonderland. You're never truly alone."),

    ("The Forgotten Seed", 
    "A seed lay forgotten in a dark corner. With time and care, it grew into the tallest tree. Never underestimate humble beginnings."),

    ("The Hummingbird's Quest", 
    "A hummingbird traveled far, seeking the sweetest nectar. She found it in her own garden. Sometimes, what we seek is closer than we think."),

    ("The Time-Telling Flower", 
    "A flower opened at sunrise and closed at sunset. It reminded everyone to value time."),

    ("The Ambitious Ant", 
    "An ant wanted to move a mountain. Every day, it moved a tiny grain. Its determination inspired the forest to help. Believe and you'll achieve."),

    ("The Grateful Tortoise", 
    "A tortoise thanked every step it took. It enjoyed the journey more than the destination. Gratitude makes every moment special."),

    ("The Playful Shadows", 
    "Shadows played and changed with the sun's position. They taught kids that change is a part of life."),

    ("The Painted Sky", 
    "The sky felt plain. At night, stars painted stories on it. Darkness brings out beauty."),

    ("The Lonely Pinecone", 
    "A pinecone felt lonely on the ground. But one day, it sprouted into a magnificent pine. Every phase is temporary."),

    ("The Friendly Moon", 
    "The moon, being kind, listened to night-time secrets of animals. It shone brighter with their trust. Kindness illuminates."),

    ("The Proud Mountain", 
    "A mountain felt proud standing tall. Then it saw the vast sky and realized humility. There's always something bigger."),

    ("The Spinning Top", 
    "A top spun fast, blurring its colors. When it slowed, its true colors showed. Sometimes, slowing down brings clarity."),

    ("The Whispering Wind", 
    "The wind carried messages from far lands, reminding everyone to listen to stories of others. Listening connects hearts."),

    ("The Watchful Lighthouse", 
    "A lighthouse stood tall, guiding ships. It showed the value of being a beacon for others."),

    ("The Singing Brook", 
    "A brook sang songs as it flowed, turning the valley musical. It's the small joys that make life beautiful."),

    ("The Laughing Stars", 
    "Stars giggled at night, making the sky twinkle. They reminded all to find joy in darkness.")
]

home_item_list = [
    ("Squeaky toy", "A colorful toy that squeals like a mischievous mouse when you squeeze it!"),
    ("Rubber duck", "A sunny yellow duck that loves to float in the bathtub, sometimes wearing sunglasses!"),
    ("Slime", "A gooey, stretchy blob that feels like alien boogers!"),
    ("Kaleidoscope", "A magical telescope that shows a festival of dancing colors and shapes!"),
    ("Cuckoo clock", "A quirky wooden clock with a bird that pops out to announce the time with a 'cuckoo'!"),
    ("Whoopie cushion", "A sneaky pillow that lets out a hilarious fart sound when someone sits on it!"),
    ("Magic 8-ball", "A mystical black ball that answers your yes-or-no questions with cryptic messages!"),
    ("Slinky", "A metal or plastic spring that tiptoes down stairs like a wobbly robot!"),
    ("Bubble wrap", "A sheet of popping joy that makes a tiny 'pop' sound when you press the bubbles!"),
    ("Wind-up toy", "A little toy that scuttles across the floor with jerky movements when wound up!"),
    ("Jellybean jar", "A transparent jar filled with rainbow-colored candies, each with a surprise flavor!"),
    ("Magnet", "A magical piece that pulls metal things towards it as if whispering secrets!"),
    ("Snow globe", "A miniature winter wonderland trapped inside a crystal ball!"),
    ("Music box", "A tiny box that plays enchanting melodies when opened, like fairy whispers!"),
    ("Bouncy ball", "A rubbery ball that springs back with joy every time you throw it down!"),
    ("Balancing bird", "A mysterious bird toy that can balance on its beak without falling over!"),
    ("Glow sticks", "A stick that lights up in neon colors, turning any room into a disco party!"),
    ("Whoopee whistle", "A tiny instrument that makes a hilarious 'whoo' sound when you blow into it!"),
    ("Sticky hand", "A stretchy, colorful hand that sticks to walls and snatches things like a mischievous ghost!"),
    ("Pinwheel", "A spinning wheel of colors that dances in the breeze like a daydream!"),
    ("Play-dough", "A moldable, colorful dough that you can shape into anything from monsters to cupcakes!"),
    ("Finger puppet", "A tiny creature that comes to life when you slide it onto your finger!"),
    ("Yoyo", "A spinning toy on a string that goes up and down, like a mini circus act!"),
    ("Fake spider", "A creepy-crawly plastic critter that can give anyone a silly scare!"),
    ("Jack-in-the-box", "A box with a surprise jester inside that pops out to the tune of a song!"),
    ("Magic wand", "A sparkly stick that can turn anyone into a frog – or maybe just make them giggle!"),
    ("Flarp noise putty", "A squishy putty that makes the funniest, tootiest sounds when you press it!"),
    ("Kazoo", "A small musical device that buzzes like a bumblebee when you hum into it!"),
    ("Disappearing ink", "A mischievous liquid that looks like ink but vanishes into thin air!"),
    ("Toy binoculars", "A pair of mini glasses that make far away things look like they're right in front of you!"),
    ("Prism", "A crystal that splits sunlight into a rainbow, as if it's holding a piece of magic!"),
    ("Feather", "A soft, tickly thing that once belonged to a bird and can make you giggle when brushed against your skin!"),
    ("Harmonica", "A pocket-sized instrument that wails like a train when you blow into it!"),
    ("Gag glasses", "Giant spectacles with a fake nose and mustache attached, turning you into a comical detective!"),
    ("Toy parachute", "A tiny person with a parachute that glides down gracefully when thrown in the air!"),
    ("Echo microphone", "A mic that repeats everything you say in a funny, echoey voice!")
]

animal_list = [
    ("Elephant", "A giant, gentle creature with big floppy ears and a long nose called a trunk which it uses to pick things up."),
    ("Kangaroo", "A bouncy animal from Australia with a big pouch to carry its baby, called a joey."),
    ("Giraffe", "The tallest animal with a super long neck to reach the treetop leaves."),
    ("Penguin", "A waddling, tuxedo-wearing bird that loves to slide on ice."),
    ("Flamingo", "A pink bird that stands on one leg and loves to dance."),
    ("Hippopotamus", "A big, round animal that spends most of its time in the water and has a giant mouth."),
    ("Narwhal", "A unicorn of the sea with a long, spiral horn."),
    ("Platypus", "A funny-looking creature with a duck's bill, a beaver's tail, and webbed feet."),
    ("Sloth", "A slow-moving animal that hangs upside down in trees and takes long naps."),
    ("Chameleon", "A lizard that can change colors and has swirly eyes."),
    ("Peacock", "A show-off bird with a huge, colorful tail it spreads out like a fan."),
    ("Porcupine", "A spiky creature that shoots out quills when it feels threatened."),
    ("Zebra", "A horse in striped pajamas."),
    ("Octopus", "An eight-armed sea creature that squirts ink and changes colors."),
    ("Meerkat", "A curious animal that stands on its hind legs and looks around like a little guard."),
    ("Walrus", "A big, blubbery sea animal with huge, long teeth called tusks."),
    ("Aardvark", "A digging animal with a long snout and sticky tongue to catch ants."),
    ("Pufferfish", "A fish that blows up like a balloon when it gets scared."),
    ("Toucan", "A bird with a big, colorful beak that loves to eat fruit."),
    ("Ferret", "A playful, slinky-like creature with a love for tunnels."),
    ("Llama", "A fluffy, long-necked animal that sometimes spits when annoyed."),
    ("Tarsier", "A tiny primate with HUGE eyes and fingers, great for clinging onto branches."),
    ("Axolotl", "A smiling water creature with feathery gills on the sides of its head."),
    ("Armadillo", "A critter with a suit of armor, rolling into a ball when scared."),
    ("Proboscis Monkey", "A monkey with a super long, funny nose."),
    ("Mandrill", "A monkey with a bright blue and red face."),
    ("Koala", "A sleepy, cuddly creature that loves to munch on eucalyptus leaves."),
    ("Tapir", "A forest animal with a funny, trunk-like nose."),
    ("Dik-dik", "A tiny antelope with a funny name and big eyes."),
    ("Blobfish", "A squishy, jelly-like fish that looks grumpy."),
    ("Naked Mole Rat", "A hairless, wrinkly rodent that lives underground."),
    ("Hedgehog", "A small, round animal covered in spiky quills."),
    ("Ostrich", "A big bird that runs really fast but can't fly."),
    ("Panda", "A chubby, black and white bear that munches on bamboo all day."),
    ("Lemur", "A playful primate with big, round eyes and a striped tail."),
    ("Star-nosed Mole", "A mole with a weird, star-shaped nose.")
]

mistakes_list = [
    "Pouring too much cereal into a bowl, causing it to overflow when milk is added.",
    "Writing letters backwards, like 'b' as 'd' or 'p' as 'q'.",
    "Trying to wash electronics or toys under running water, risking damage.",
    "Forgetting to tie shoelaces and tripping over them while playing.",
    "Using permanent markers on walls thinking they're just like regular crayons.",
    "Feeding pets people food, unaware of potential dangers to the animal.",
    "Attempting to carry too many toys at once, leading to drops and breakages.",
    "Spilling paint on the floor while engrossed in a creative project.",
    "Running with scissors or other sharp objects, risking injury.",
    "Wearing mismatched socks or shoes out of excitement or inattention.",
    "Overwatering plants thinking it will make them grow faster.",
    "Touching hot surfaces out of curiosity, like a stove or iron.",
    "Leaving refrigerator door open, causing food to spoil.",
    "Skipping steps or pages in a board game, leading to confusion.",
    "Climbing on furniture or shelves and risking a fall.",
    "Placing toys in the toilet, thinking it's a fun water game.",
    "Eating something without checking if it's edible, like play-dough or a crayon.",
    "Telling tall tales or small fibs, thinking adults won't catch on.",
    "Forgetting to apply sunscreen on sunny days, risking sunburn.",
    "Not understanding the concept of money, offering pennies for expensive toys.",
    "Dressing inappropriately for the weather, like wearing a summer dress in snow.",
    "Drawing on their own skin with markers, thinking it's a permanent tattoo.",
    "Leaving toys scattered around, causing trip hazards for family members.",
    "Putting fingers in door hinges, risking painful pinches.",
    "Not sharing toys with friends, leading to conflicts and hurt feelings.",
    "Blowing up a balloon too much and being startled when it pops loudly.",
    "Throwing things indoors, unaware of the potential damages or risks.",
    "Using too much toothpaste, thinking more will clean teeth faster.",
    "Bringing outside critters indoors, like frogs or insects, thinking they'd make good pets.",
    "Mixing different household liquids out of curiosity, unaware of potential reactions.",
    "Not looking both ways before crossing the street, risking danger.",
    "Attempting to bake or cook without adult supervision, leading to potential hazards.",
    "Believing they can fly like superheroes and attempting risky jumps from heights.",
    "Mispronouncing or misunderstanding words and getting embarrassed in conversations."
]

tricks_list = [
    "Making a coin 'disappear' behind their ear, only to magically bring it back.",
    "The classic trick of pulling a colorful handkerchief out of an empty bag.",
    "Pouring water into a cup, turning it upside down, and the water being mysteriously gone.",
    "Cutting a piece of rope in half and magically restoring it to its original length.",
    "Turning a plain piece of paper into a colorful picture with just a wave of a wand.",
    "Making a toy levitate in the air with the 'power' of a magic word.",
    "Changing the color of a liquid in a transparent glass just by shaking it.",
    "Creating shadows on a wall that look like animals using only hands and a flashlight.",
    "Guessing the number a child is thinking of between 1 and 10 with a mysterious crystal ball.",
    "Transforming a rubber ball into a square cube with a snap of the fingers.",
    "Floating a paper clip on the surface of water using only the power of surface tension.",
    "Showing how mixing two different colors of clay can create a totally new color.",
    "Bending a straight pencil without breaking it, using the refraction in a glass of water.",
    "Drawing a picture that looks different when viewed from another angle using optical illusions.",
    "Making a 'teleporting' coin move from one hand to another without passing it.",
    "Creating a mini volcano eruption using baking soda and vinegar.",
    "Revealing hidden messages written in invisible ink using the heat from a light bulb.",
    "Growing a 'magic' crystal overnight from a simple solution of salt and water.",
    "Floating a ping pong ball in the air using the power of a hair dryer.",
    "Building a paper airplane that can loop-the-loop with a special fold technique.",
    "Mixing oil and water in a bottle and watching them magically separate.",
    "Creating musical notes using different levels of water in glass bottles and tapping them.",
    "Balancing a coin on the edge of a dollar bill without it falling.",
    "Making a balloon stick to the wall using static electricity after rubbing it on hair.",
    "Transforming a square piece of paper into a beautiful origami animal.",
    "Solving a puzzle cube in seconds after mixing it up, showcasing the art of algorithms.",
    "Turning milk into a solid form using simple household ingredients.",
    "Showing how a prism can split a ray of light into a beautiful spectrum of colors.",
    "Demonstrating how a magnet can push and pull objects without touching them.",
    "Creating a rainbow in a glass of water using just a flashlight.",
    "Building a bridge using only paper and tape that can hold a toy car.",
    "Changing the pitch of a voice using a balloon filled with different gases like helium.",
    "Generating electricity by rubbing a balloon on hair and making a small light bulb glow.",
    "Using simple household items to create a whirlpool in a bottle."
]

prank_list = [
    "Place a small piece of clear tape over the bottom of a computer mouse so it doesn't work.",
    "Switch around the order of shoes in the closet for a moment of confusion.",
    "Put a toy spider under someone's pillow and watch their reaction when they lift it up.",
    "Offer to serve a drink and give them a cup filled with water containing a plastic ice cube with a fake bug inside.",
    "Attach a long piece of clear thread to a toy and move it from a distance, making it look like it's moving on its own.",
    "Place a whoopee cushion on someone's chair just before they sit down.",
    "Swap the cereal bags inside their boxes, so when someone pours out their morning cereal, they get a surprise.",
    "Tightly twist a rubber band around the handle of the sink's sprayer, so it sprays water when turned on.",
    "Switch the salt and sugar containers, so morning coffee gets a salty twist.",
    "Leave a note under someone's pillow saying 'You're being watched' and watch them look around the room.",
    "Stick googly eyes on all the items in the fridge so they 'stare' when the door is opened.",
    "Replace the contents of an Oreo cookie with toothpaste and offer it as a treat.",
    "Add food coloring to a jug of milk for a colorful breakfast surprise.",
    "Turn all the framed photos or artworks in the house upside-down.",
    "Put a small toy or item inside someone's shoe for a foot-tickling surprise.",
    "Inflate a balloon and hide it behind a door, so it pops out when someone opens the door.",
    "Stick a balloon to the tailpipe of a car (only with adult supervision and ensuring no damage).",
    "Place clear plastic wrap across a doorway at chest height for a surprise walk-through.",
    "Quietly play a recording of a strange noise and hide the source, watching the bemused reactions.",
    "Use a harmless, washable marker to draw a tiny smiley face on the back of someone's hand while they sleep.",
    "Create a fake remote by wrapping a block of wood in paper and hand it over when someone wants to change the TV channel.",
    "Place a stuffed toy on someone's bed, pretending it's 'resting' and needs not to be disturbed.",
    "Hide a small alarm clock in the room, set to go off at an unexpected time.",
    "Replace someone's bookmark with a silly note or picture.",
    "Put tiny stickers on the bottom of someone's slippers or shoes so they leave funny footprints.",
    "Carefully remove the filling from a pillow and replace it with inflated balloons.",
    "Stick a funny note on the back of someone's shirt without them noticing.",
    "Leave a trail of toy footprints leading to a hidden 'treasure' or surprise.",
    "Attach a helium-filled balloon to someone's bed, so it floats up when they pull back the covers.",
    "Fill an empty sunscreen bottle with vanilla yogurt and pretend to eat it.",
    "Tell someone there's an 'invisible' pet (like a unicorn) in the garden and have them search for it.",
    "Replace the batteries in a toy with empty ones and act surprised when it doesn't work.",
    "Offer a hand (fake toy one, of course) when someone asks for 'a hand' with something.",
    "Hide a tiny toy under a cup, shuffle the cups around, and have someone guess where it's hiding.",
    "Put jelly in a drinking straw, let it set, and then offer the straw with a drink.",
    "Carefully put a small amount of washable paint on the soap bar, so it colors hands when used."
]

relation_list = [
    "Mrs. Miller, the kind-hearted kindergarten teacher with silver curls and glasses that always seem to slide down her nose, who always has a story or song up her sleeve.",
    "Grandpa Joe, with his deep laughter lines and stories of 'the good old days', often seen with a fishing rod or a wooden toy he crafted in his shed.",
    "Buddy, the family's golden retriever, always wagging his tail, his fur as soft as cotton, and always ready to play fetch or be a comforting presence.",
    "Ms. Karen, the school librarian with her owl-like glasses, a passion for fairy tales and an uncanny ability to recommend the perfect book.",
    "Mr. Roberts, the friendly neighbor with a garden full of sunflowers, who hands out homemade cookies every Saturday and knows all the local bird songs.",
    "Aunt Clara, with her collection of colorful scarves and jingling bracelets, who tells tales of her travels and teaches dances from all over the world.",
    "Tommy, the same-aged friend from next door, with boundless energy, a collection of action figures, and always an idea for a new adventure game.",
    "Miss Gina, the ballet instructor in her elegant tutu, who moves with grace and teaches the art of dance with patience and enthusiasm.",
    "Mr. Green, the school bus driver with a cap always askew, a jolly demeanor, and a warm greeting for every child as they step onto his bus.",
    "Mom, with her comforting scent and warm hugs, who reads bedtime stories, makes the best sandwiches, and knows just how to soothe a bad day away.",
    "Dad, with his strong hands and reassuring voice, who builds forts out of blankets, teaches how to ride a bike, and tells jokes that make everyone groan.",
    "Fluffy, the family cat, with sleek black fur and a regal demeanor, often found sunning by the window or playfully chasing a toy mouse.",
    "Coach Mike, the enthusiastic soccer coach with a whistle around his neck, always encouraging, teaching teamwork and the joys of running in an open field.",
    "Ms. Lila, the art teacher with paint on her apron and a twinkle in her eye, introducing the world of colors, shapes, and the magic of creativity.",
    "Uncle Ben, the one with a penchant for magic tricks and surprise visits, always with a new riddle or a small toy from his many trips.",
    "Sara, the friendly cafeteria lady, with her hair in a net, who serves lunches with a smile and always sneaks in an extra fruit for the favorites.",
    "Mrs. Peters, the school principal with a stern yet kind face, maintaining order in school but also known to join in for a dance or a game occasionally.",
    "Sophie, the older sister by four years, with her collection of dolls, secret diaries, and the ability to both tease and protect fiercely.",
    "Jack, the gentle giant of a janitor at school, with keys jangling from his belt and stories of hidden school treasures, always ready with a helping hand.",
    "Grandma Ana, with her old-world tales, scents of freshly baked bread, a comforting lap, and soft lullabies sung in a language of old.",
    "Penny, the little friend from ballet class with a penchant for pink, twirling together and sharing dreams of becoming famous dancers.",
    "Dr. Smith, the pediatrician with a friendly demeanor, a drawer full of stickers, and the ability to make check-ups less scary and more fun.",
    "Mr. Grey, the postman with a bag full of letters, a cheerful whistle, and news of the outside world, sometimes bringing packages with surprises inside.",
    "Lily, the cousin from out of town, always with a new board game to share, endless tales of her city life, and a matching sense of mischief.",
    "Mr. Hudson, the elderly man at the park feeding pigeons, with tales of wars and old city tales, sharing wisdom and occasionally a candy.",
    "Mrs. Chang, the music teacher, with her piano tunes and encouraging nods, teaching the joys of rhythms, beats, and the first notes on a recorder.",
    "Charlie, the ice cream vendor with his jingling truck, known routes, and the magical ability to appear just when a summer day gets too hot.",
    "Aunt Mia, the scientist with a lab coat, who sends postcards of animals, rocks, and stars, sparking curiosity about the world and how it works.",
    "Sammy, the class clown, with wild hair and a wilder sense of humor, always with a joke, a prank, or a funny face up his sleeve.",
    "Mrs. Johnson, the school counselor with a room full of toys and books, always ready to listen, comfort, and guide through the maze of feelings.",
    "Max, the kid with a wheelchair and a radiant smile, teaching lessons of resilience, joy, and that differences make us unique and special.",
    "Miss Ellie, the young woman at the local bookstore, with recommendations for young readers and tales of far-off worlds and adventurous quests.",
    "Mama Rosa, the lady at the community church, always with a kind word, a story from the Bible, and a loving embrace for every child.",
    "Bobby, the older brother's friend, with his video games, cool gadgets, and the aura of 'grown-up' mystery, occasionally letting the little one join in their games."
]


dilemma_dict = {
    "Choosing a toy at the store": ["Pick the most expensive toy", "Choose a toy within budget", "Can't decide and chooses nothing", "Chooses multiple toys"],
    "Friend wants the same toy they're playing with": ["Shares the toy", "Refuses to share", "Gives the toy up entirely", "Suggests another toy instead"],
    "Doesn't want to eat vegetables": ["Eats them anyway", "Refuses and goes hungry", "Only eats a few", "Throws a tantrum"],
    "Finds a lost toy at the park": ["Takes it home", "Leaves it where it is", "Tells an adult", "Gives it to another child"],
    "Wants to play but it's bedtime": ["Stays up secretly", "Goes to bed grudgingly", "Throws a tantrum", "Bargains for five more minutes"],
    "Feels like watching TV, but homework is pending": ["Watches TV anyway", "Does homework first", "Ignores both and plays", "Does half the homework then watches TV"],
    "Spills juice on the carpet accidentally": ["Hides the mess", "Tries to clean it up", "Tells an adult immediately", "Blames it on someone else"],
    "Wants two different ice cream flavors but can only pick one": ["Chooses one and feels sad", "Chooses one happily", "Begs for both", "Decides not to have any ice cream"],
    "Friend broke their toy": ["Gets upset with friend", "Understands it was an accident", "Demands friend buys a new one", "Stops playing with that friend"],
    "Sees a child being bullied": ["Joins the bully", "Ignores it", "Stands up for the child", "Tells an adult"],
    "Forgot their lunch at home": ["Shares with a friend", "Stays hungry", "Asks the teacher for help", "Tries to take someone else's lunch"],
    "Doesn't want to brush teeth before bed": ["Doesn't brush", "Brushes quickly", "Turns it into a game to make it fun", "Complains but brushes anyway"],
    "Wants to play on the swing but someone else is on it": ["Pushes the other child", "Asks to take turns", "Waits patiently", "Cries or throws a tantrum"],
    "Has a secret they're not sure whether to share": ["Tells a friend", "Keeps it to themselves", "Shares with an adult", "Writes it down and hides it"],
    "Lost a game and feels like crying": ["Cries openly", "Holds back tears", "Accuses the other player of cheating", "Asks for a rematch"],
    "Sibling wants to play with their toy": ["Shares it", "Hides the toy", "Allows sibling to play under conditions", "Breaks the toy so no one can use it"],
    "Drops someone else's ice cream cone": ["Offers their own to them", "Laughs", "Apologizes and feels guilty", "Denies it was their fault"],
    "Sees a friend steal something": ["Confronts the friend", "Steals something too", "Tells an adult", "Ignores it"],
    "Receives a gift they don't like": ["Pretends to like it", "Expresses dislike immediately", "Gives it away secretly", "Complains to others about it"],
    "Is afraid of a dog nearby": ["Runs away screaming", "Asks owner if it's safe", "Stands still and hopes dog goes away", "Tries to pet the dog without asking"],
    "Doesn't understand homework": ["Gives up", "Asks a parent for help", "Guesses the answers", "Tells teacher they didn't understand"],
    "Gets paint on their hands": ["Wipes it on clothes", "Asks for help cleaning up", "Continues painting with hands", "Freaks out and demands it be cleaned"],
    "Is offered candy by a stranger": ["Takes the candy", "Refuses and walks away", "Talks to the stranger", "Tells an adult"],
    "Sees someone drop money": ["Picks it up and keeps it", "Picks it up and returns it", "Ignores it", "Tells a friend about it"],
    "Wants to play a game but it's rated above their age": ["Plays it secretly", "Asks for permission", "Plays a different game", "Throws a fit to be allowed"],
    "Has a crush on a classmate": ["Tells them", "Keeps it a secret", "Tells a friend", "Avoids the classmate"],
    "Sees a toy they're not allowed to play with": ["Plays with it secretly", "Ignores it", "Asks for permission", "Throws a fit to be allowed"],
    "Has to choose between two friends to invite for a playdate": ["Chooses one and tells the other they were busy", "Invites both", "Doesn't invite anyone", "Invites one and ignores the other"],
    "Finds a spider in their room": ["Kills it", "Screams for help", "Catches and releases it outside", "Ignores it"],
    "Doesn't want to shower": ["Avoids showering", "Complains but showers anyway", "Turns shower into playtime", "Promises to shower later"],
    "Sees someone cheating in a game": ["Tells on them", "Ignores it", "Cheats as well", "Confronts the cheater privately"],
    "Friend tells them a lie they know isn't true": ["Calls out the friend", "Pretends to believe it", "Laughs it off", "Shares the lie with others"],
    "Sibling gets a reward they wanted": ["Feels jealous and upset", "Is happy for them", "Bargains to share the reward", "Complains to parents"],
    "Brought too many books to carry": ["Struggles to carry them all", "Asks for help", "Leaves some behind", "Drops them on purpose"],
    "Has a piece of cake but a friend has none": ["Eats it all by themselves", "Shares half with the friend", "Gives the whole piece to the friend", "Hides it to eat later"],
    "Friend is playing with a toy they're afraid of (like a bug toy)": ["Avoids the friend", "Tells the friend to stop", "Pretends to be brave", "Tells an adult"],
    "Lost a library book": ["Tells the teacher", "Hides the fact and worries", "Tries to replace it", "Blames someone else"],
    "Is offered a seat in a crowded place": ["Takes the seat", "Offers it to someone else", "Refuses and stands", "Takes the seat but feels guilty"],
    "Finds an injured bird in the yard": ["Tries to care for it", "Tells an adult", "Leaves it alone", "Pokes at it out of curiosity"],
    "Sees a friend playing with matches": ["Joins the friend", "Tells them to stop", "Grabs the matches away", "Tells an adult"],
    "Is told a secret they're not supposed to share": ["Keeps the secret", "Tells one close friend", "Shares with everyone", "Tells an adult because they're worried"],
    "Wants to wear a costume to school but it's not costume day": ["Wears it proudly", "Decides against it", "Hides it in backpack to wear later", "Cries because they're unsure"],
    "Friend's ball goes into a prohibited area": ["Goes to retrieve it", "Tells the friend it's gone", "Asks an adult for help", "Claims they don't know where it went"],
    "Is given extra change at the store": ["Keeps it", "Returns it", "Buys something else", "Gives it to a friend"],
    "Receives a gift from a friend they already have": ["Pretends to be surprised", "Tells the friend", "Swaps it with someone else", "Keeps both"],
    "Wants to use the computer but has a screen time limit": ["Respects the limit", "Sneaks extra time", "Bargains for more time", "Complains loudly about the limit"],
    "Accidentally drew on the wall": ["Tries to clean it", "Hides it", "Blames a sibling", "Tells the truth when asked"],
    "Friend falls and they can't help laughing": ["Apologizes immediately", "Helps the friend up without apologizing", "Continues laughing", "Denies they were laughing"],
    "Sees a friend's pet run away": ["Chases the pet", "Tells the friend", "Hides and hopes it comes back", "Ignores it"],
    "Is scared during a thunderstorm": ["Seeks comfort from parents", "Hides under blankets", "Tries to comfort a younger sibling", "Claims they're not scared at all"],
    "Breaks something at a friend's house": ["Tells the friend", "Hides it", "Tries to fix it", "Blames someone else"],
    "Is asked to perform in front of class but is shy": ["Refuses to do it", "Does it but very nervously", "Pretends to be sick", "Practices a lot to be prepared"],
    "Finds someone's diary": ["Reads it", "Returns it without reading", "Hides it", "Tells friends about it"],
    "Missed a fun event because of sickness": ["Feels sorry for themselves", "Asks friends about it", "Makes up a fun story about what they did instead", "Tries to forget about it"],
    "Gets a lower grade than expected": ["Studies harder next time", "Feels upset but doesn't act", "Blames the teacher", "Hides the grade from parents"],
    "Sees a new kid sitting alone": ["Joins them", "Ignores them", "Tells friends to join them", "Makes fun of them for being alone"],
    "Friend made a craft gift that is not pretty": ["Praises it genuinely", "Avoids commenting on it", "Critiques it", "Laughs at it"],
    "Wants to play outside but it's raining": ["Plays in the rain", "Stays inside grudgingly", "Makes a fun indoor game", "Watches the rain from a window"],
    "Is invited to two birthday parties at the same time": ["Chooses one and attends", "Tries to attend both briefly", "Declines both to avoid choosing", "Attends one and lies about the reason to the other"],
    "Sees a friend's toy they've wanted for a long time": ["Asks to play with it", "Tries to trade for it", "Feels jealous but says nothing", "Tells the friend they want the same toy"],
    "Loses a race and feels disappointed": ["Tries again", "Congratulates the winner", "Claims there was a mistake", "Avoids racing in the future"],
    "Wants to climb a tree but is scared": ["Tries to climb a little bit", "Decides against it", "Asks for help", "Watches others climb"],
    "Is told to finish food but is full": ["Eats all and feels too full", "Hides some of the food", "Says they're full and stops", "Complains about the food"],
    "Is given a task they feel is too hard": ["Attempts it anyway", "Seeks help", "Avoids doing it", "Complains about it being unfair"],
    "Hears a scary noise at night": ["Investigates the noise", "Hides under covers", "Calls for parents", "Uses a flashlight to look around"],
    "Sibling is getting more attention": ["Acts out for attention", "Feels sad but says nothing", "Tries to be helpful to get praise", "Tells parents how they feel"],
    "Doesn't want to wear a hat in the cold": ["Goes without and feels cold", "Wears it grudgingly", "Chooses a different hat", "Complains about the hat the whole time"],
    "Is asked to sing a song in front of relatives": ["Sings shyly", "Sings confidently", "Refuses", "Pretends they don't know any songs"],
    "Wants to buy a toy but doesn't have enough allowance": ["Saves up for next time", "Begs parents for more money", "Tries to negotiate price", "Feels upset and buys nothing"],
    "Sees a friend littering": ["Confronts the friend", "Picks it up themselves", "Ignores it", "Joins in and litters too"],
    "Offered food they've never tried before": ["Tries it bravely", "Politely declines", "Makes a face and refuses", "Asks a friend's opinion first"],
    "Finds a lost phone on the playground": ["Turns it into lost and found", "Tries to find the owner by asking around", "Keeps it", "Plays with it then leaves it"],
    "Wants to read a book that's too hard for them": ["Tries to read it anyway", "Asks someone to read it with them", "Chooses an easier book", "Gets frustrated and gives up"],
    "Is given chores they don't like": ["Does them without complaint", "Tries to trade chores with a sibling", "Avoids doing them", "Does them but complains throughout"],
    "Accidentally overfeeds a pet": ["Tells an adult", "Tries to remove extra food", "Waits and hopes for the best", "Blames it on a sibling"],
    "Has to pick a team in class and doesn't know who to choose": ["Picks at random", "Chooses closest friends", "Lets others pick first", "Tries to avoid the responsibility"],
    "Someone tells a joke they don't understand": ["Laughs along", "Asks for an explanation", "Says they don't get it", "Ignores it"],
    "Has to participate in a sport they're bad at": ["Tries their best anyway", "Avoids participating", "Makes jokes about their own skills", "Gets upset and doesn't try"],
    "Is given too much homework": ["Attempts to complete it all", "Does as much as they can and then tells the teacher", "Avoids it and plays instead", "Asks a sibling for help"],
    "Sees a friend crying": ["Offers comfort", "Asks what's wrong", "Feels awkward and avoids them", "Tells an adult"],
    "Is teased for wearing glasses": ["Responds with a witty comeback", "Feels hurt and says nothing", "Tells a teacher", "Avoids the person teasing"],
    "Takes a toy to school and it's now missing": ["Looks for it", "Accuses someone of taking it", "Asks friends for help", "Cries or gets upset"],
    "Spends all their time on one homework question and doesn't finish the rest": ["Hands in incomplete work", "Guesses the rest of the answers", "Asks for an extension", "Claims they lost the homework"],
    "Forgets their lines in a school play": ["Makes up something on the spot", "Stays silent or mumbles", "Whispers to a fellow actor for help", "Runs off the stage"],
    "Invited to play a game they've never played before": ["Joins in eagerly to learn", "Watches first before playing", "Declines because they're unsure", "Claims to know it but doesn't"],
    "Draws a picture and another student makes fun of it": ["Redraws it", "Defends their original drawing", "Throws it away", "Makes fun of the other student's drawing"],
    "Is asked to help set up for a party": ["Helps enthusiastically", "Claims they're too tired", "Helps but expects a reward", "Hides to avoid helping"],
    "Knows a friend cheated off their test": ["Confronts the friend", "Tells the teacher", "Changes their answers next time", "Says nothing"],
    "Receives more candy than a sibling during Halloween": ["Shares some candy", "Keeps it all", "Trades candies with them", "Brags about their candy haul"],
    "Asked to donate a toy they don't play with anymore": ["Chooses a toy happily", "Doesn't want to give any away", "Chooses a broken toy", "Asks a sibling to choose first"],
    "Wants to watch a show but the TV is occupied": ["Asks to share the TV time", "Waits patiently", "Throws a tantrum", "Tries to distract the other viewer"],
    "Hears someone gossiping about a friend": ["Defends the friend", "Listens quietly", "Shares the gossip with others", "Tells the friend"],
    "Asked to taste a dish they helped cook but don't want to eat": ["Tastes it to be polite", "Pretends to taste it", "Declines openly", "Says they're not hungry"],
    "Sees a toy in a friend's bag they want": ["Asks to see or play with it", "Takes it without asking", "Ignores it", "Tells other friends about it"],
    "Friend offers to do their homework for them": ["Accepts the offer", "Declines and does it themselves", "Lets friend do some but not all", "Tells the teacher"],
    "Is afraid to go down a slide at the park": ["Tries it with a friend", "Avoids it entirely", "Watches others and then decides", "Cries or gets upset"],
    "Wants a pet but parents are against it": ["Begs incessantly", "Promises to take care of it fully", "Feels upset but accepts", "Tries to bring home a stray animal"],
    "Loses a game they really wanted to win": ["Asks for a rematch", "Congratulates the winner", "Claims the game was unfair", "Stops playing entirely"],
    "Wants to eat dessert before dinner": ["Sneaks a bite", "Asks permission", "Eats dinner quickly to get to dessert", "Whines or complains"],
    "Borrows something and it breaks": ["Tells the owner immediately", "Tries to fix it", "Replaces it", "Hides it or denies responsibility"],
    "Wants to stay up past bedtime": ["Tries to negotiate with parents", "Sneaks staying awake in bed", "Throws a fit", "Reads quietly under covers"],
    "Is nervous about a doctor's appointment": ["Voices their fears", "Tries to act brave", "Hides or avoids going", "Seeks comfort from a toy or book"],
    "Doesn't want to brush teeth before bed": ["Does it after a reminder", "Avoids it and sneaks to bed", "Argues about it", "Promises to do it in the morning"],
    "Friend has a toy they've been told they're not allowed to have": ["Plays with it at friend's house", "Tells parents about it", "Feels jealous but says nothing", "Asks the friend to hide it when they visit"],
    "Is given money to buy something for a school project but wants to spend it on candy": ["Buys candy and hides it", "Saves money for project", "Buys candy and shares with friends", "Tells parents and asks for advice"],
    "Wants to play an outdoor game but it's too hot": ["Plays for a short time", "Plays in the shade", "Chooses an indoor game instead", "Complains about the weather"],
    "Accidentally hurts a friend while playing": ["Apologizes immediately", "Claims it was the friend's fault", "Tries to make the friend laugh to forget", "Runs away from the situation"],
    "Spills juice on a library book": ["Tries to clean it and return", "Confesses and offers to pay for it", "Returns it without saying anything", "Hides the book and never returns it"],
    "Wants to join a club at school but none of the friends are in it": ["Joins anyway to make new friends", "Decides not to join", "Convinces a friend to join with them", "Attends a few meetings to decide"],
    "Forgets to do a chore and remembers just before bedtime": ["Does it quickly before bed", "Promises to do it first thing in the morning", "Hopes parents don't notice", "Blames it on a sibling"],
    "Wants to wear pajamas to school": ["Wears them and feels proud", "Decides against it fearing teasing", "Asks a friend to wear theirs too", "Wears them but brings a change of clothes"],
    "Sees a classmate cheating during a game": ["Tells the teacher", "Confronts the classmate", "Says nothing but avoids teaming with them", "Helps them cheat"],
    "Is scared of a bug in the room": ["Tries to get rid of it", "Calls for help", "Ignores it", "Leaves the room and refuses to come back"],
    "Receives a gift they don't like for their birthday": ["Says thank you anyway", "Expresses disappointment", "Hides it and never uses it", "Asks if they can exchange it"],
    "Friend breaks a promise they made": ["Talks to the friend about how it made them feel", "Breaks a promise in return", "Ignores the friend", "Tells other friends about it"],
    "Doesn't want to get hair cut": ["Voices their dislike but does it", "Throws a tantrum at the salon", "Suggests a different hairstyle", "Bargains to postpone it"],
    "Loses a toy and suspects a friend took it": ["Directly asks the friend", "Sneakily looks for it at the friend's house", "Tells an adult", "Takes something of the friend's in return"],
    "Is given homework over the weekend": ["Does it immediately to enjoy the rest", "Waits until Sunday night", "Does half and plans to finish the rest with a friend", "Pretends to lose it"],
    "Finds a wallet on the school bus": ["Turns it into the bus driver", "Looks inside for an ID", "Takes it to the school's lost and found", "Keeps any money found inside"],
    "Is invited to a movie they're scared of": ["Declines the invite", "Goes but brings a comfort object", "Tries to change the movie choice", "Sits through it but covers eyes often"],
    "Friend wants to swap lunches, but their food isn't as nice": ["Agrees to make the friend happy", "Declines politely", "Swaps only one item", "Suggests they share both lunches"],
    "Feels too tired for school in the morning": ["Tries to stay home sick", "Goes to school but is sluggish", "Asks for a rest before getting ready", "Tells teacher and asks for fewer tasks"],
    "Friend keeps interrupting when they're talking": ["Politely asks them to wait", "Stops talking entirely", "Interrupts the friend back", "Changes the topic"],
    "Siblings are fighting and they're caught in the middle": ["Tries to mediate the fight", "Takes one sibling's side", "Ignores and stays out of it", "Tells an adult"],
    "Doesn't know how to play a game at a friend's birthday party": ["Asks for rules and joins", "Watches others play first", "Chooses not to play", "Pretends to know but makes mistakes"],
    "Sees someone shoplift at a store": ["Tells a store employee", "Tells parents or guardian", "Ignores it", "Feels curious and considers doing it too"],
    "Receives extra change from a purchase": ["Returns the extra change", "Keeps it", "Gives it to someone else", "Donates it to a charity jar"],
    "Is asked to sing in front of class but is shy": ["Tries their best", "Declines the offer", "Asks to sing with a friend", "Pretends to be sick"],
    "Breaks something in the house": ["Confesses immediately", "Tries to fix it", "Hides it", "Blames it on a pet or sibling"],
    "Feels left out of a group at school": ["Tries to join the conversation", "Finds another group or friend", "Tells a teacher or counselor", "Stays alone and feels sad"],
    "Is asked to finish food but is already full": ["Eats it all to please adults", "Saves it for later", "Secretly throws it away", "Tells the truth about being full"],
    "Siblings are watching a show they don't like": ["Watches with them anyway", "Asks to watch something else", "Watches something in another room", "Complains until the channel is changed"],
    "Is offered help with a task they're struggling with": ["Accepts help gratefully", "Declines and tries alone", "Gets frustrated and gives up", "Watches the helper and learns for next time"],
    "Someone at school has the same outfit on": ["Compliments the other's taste", "Feels embarrassed and tries to change", "Avoids the person all day", "Laughs about it and takes a picture"],
    "Sees a lost animal on the way home": ["Tries to approach and help", "Ignores it", "Tells an adult or parent", "Feeds it but doesn't bring it home"],
    "Is asked to share a favorite toy": ["Shares willingly", "Refuses to share", "Lets friend play with it but watches closely", "Offers another toy instead"],
    "Wants to paint the walls but knows it's not allowed": ["Paints secretly and gets in trouble", "Asks for permission", "Uses paper instead", "Waits for a chance when no one's watching"],
    "Hears a scary noise in the middle of the night": ["Hides under the blanket", "Goes to parents' room", "Investigates the noise with a flashlight", "Calls out to see who it is"],
    "Forgets to pack a school lunch": ["Shares with a friend", "Buys lunch from school", "Goes hungry", "Asks teacher for help"],
    "Wants to climb a tree but is scared": ["Tries climbing a short distance", "Decides not to climb", "Asks for encouragement or assistance", "Watches friends and learns from them"],
    "Sees a friend lying to a teacher": ["Confronts the friend privately", "Supports the lie", "Tells the truth to the teacher", "Stays out of it completely"],
    "Accidentally rips a page from a school library book": ["Tells the librarian and apologizes", "Tapes it up and returns quietly", "Hides the book", "Blames someone else"],
    "Gets more allowance than usual by mistake": ["Keeps the extra money", "Tells the parents about the mistake", "Saves it for later", "Shares with siblings or friends"],
    "Finds someone else's toy at the playground": ["Takes it home", "Leaves it where it is", "Gives it to a lost and found", "Asks around to return it"],
    "Is given a chore they really dislike": ["Does it anyway without complaining", "Tries to swap chores with a sibling", "Avoids doing it", "Does a sloppy job on purpose"],
    "Siblings want to play a game they don't enjoy": ["Plays for the sake of bonding", "Suggests another game", "Refuses to play and does something else", "Pretends to be sick to avoid playing"],
    "Told to eat vegetables they don't like": ["Eats them quickly to get it over with", "Hides them under something else", "Tells the truth about disliking them", "Mixes with something tasty to mask the flavor"],
    "Wants to buy a toy but doesn't have enough money": ["Saves up until they can afford it", "Asks parents for extra chores to earn more", "Feels sad and gives up", "Tries to negotiate the price at the store"],
    "Friend plays with a new group and doesn't invite them": ["Asks the friend about it", "Feels jealous and avoids the friend", "Joins another group", "Tries to befriend the new group too"],
    "Is chosen last in a team sport at school": ["Tries their best in the game", "Feels upset and doesn't participate fully", "Asks the teacher for a different activity", "Vows to practice and get better"],
    "Spills paint on the classroom floor": ["Cleans it up immediately", "Hides it with something", "Blames it on someone else", "Asks for help from classmates"],
    "Is tempted to watch a TV show past bedtime": ["Resists and goes to bed", "Watches quietly with volume low", "Asks for permission to watch", "Watches and then oversleeps the next morning"],
    "Receives two invitations for the same day": ["Chooses the one they prefer", "Tries to attend both", "Declines both to avoid choosing", "Asks a friend for advice on what to do"],
    "Has a secret they're tempted to share": ["Tells a trustworthy friend", "Keeps it to themselves", "Writes it in a diary", "Shares anonymously online"],
    "Accidentally overfeeds a pet": ["Tries to remove the excess food", "Waits and watches the pet", "Tells an adult and asks for advice", "Ignores it"],
    "Is teased for a mistake made in class": ["Ignores the teasing", "Feels embarrassed and avoids those students", "Confronts the teasers", "Tells a teacher or counselor"],
    "Wants to play a video game but has homework": ["Does homework first then plays", "Plays a short game and then does homework", "Procrastinates and plays all day", "Sneaks in game time during homework breaks"],
    "Is scared of swimming during a pool class": ["Stays in the shallow end", "Avoids attending the class", "Tells the instructor about the fear", "Watches from the side and learns by observation"],
    "Finds a toy in the store they really want": ["Asks parents politely", "Throws a tantrum when denied", "Decides to save and buy later", "Tries to put it in the cart secretly"],
    "Is challenged by a friend to do something risky": ["Refuses and suggests something else", "Accepts the challenge without thinking", "Weighs the risks and then decides", "Distracts friend with another activity"],
    "Sees a friend being bullied": ["Steps in and defends the friend", "Tells a teacher or authority figure", "Stays out of it but comforts friend later", "Joins the bully out of peer pressure"]
}

