postive_prompt_samples = [
    "Bubbly flute melodies dancing over the gentle strumming of a ukulele, like butterflies fluttering in a sunny meadow.",
    "A playful accordion setting the scene for a whimsical circus, with jesters juggling and elephants parading.",
    "Cheerful piano notes sprinkling like raindrops, with a soft violin humming a lullaby in the background.",
    "Mischievous plucks of a double bass, reminiscent of a sneaky cat prowling in the moonlight.",
    "A bright and jumpy trumpet tune, evoking images of a parade marching down a candy-colored street.",
    "Tinkling glockenspiel notes paired with gentle harp, painting a scene of twinkling stars and dreamy nights.",
    "A lively banjo strumming away, taking kids on a fun-filled hayride on a bright autumn day.",
    "Pounding drum beats echoing the footsteps of dinosaurs, as the didgeridoo hums the ancient songs of the earth.",
    "Majestic horn blasts heralding the arrival of a royal king and queen, with cymbals crashing in celebration.",
    "Enchanting woodwinds weaving tales of fairies and elves frolicking in a magical forest.",
    "A smooth clarinet leading a jazzy tune, as if mice in bow ties were having a grand ball.",
    "Rapid maracas shaking to the rhythm of a sizzling summer fiesta, with colorful dancers swirling around.",
    "Energetic electric guitar riffs, taking kids on a rock 'n' roll rollercoaster of fun and thrill.",
    "Calming pan flute melodies floating over a babbling brook, accompanied by chirping crickets and croaking frogs.",
    "A whimsical kalimba tune, reminiscent of a dreamy African safari with giraffes and zebras grazing.",
    "Swooshing synthesizers creating a soundscape of soaring spaceships and intergalactic travel.",
    "The gentle lull of a cello, conjuring images of graceful swans gliding over a serene lake.",
    "Chirpy recorder notes hopping and skipping, as if cheeky monkeys were playing hide and seek.",
    "A frothy saxophone spinning tales of a bustling city, with taxis honking and pedestrians chatting.",
    "The fast-paced beat of bongos, picturing a lively beach party with kids building sandcastles and chasing waves.",
    "Mystical chimes and bells ringing out, as wizards and witches cast their spells in an ancient castle.",
    "The soft strum of a mandolin painting a picturesque Italian village, with families gathering for a feast.",
    "Harmonious hum of a harmonica, reminiscent of cowboys and campfires under a vast starry sky.",
    "Twirling tunes of a sitar, taking children on a magic carpet ride over bustling Arabian bazaars.",
    "Pulsating beats of electronic drums, setting the stage for futuristic robot dances and neon lights.",
    "A cozy accordion serenading a romantic French café, with wafts of fresh pastries and clinking coffee cups.",
    "Echoing bamboo flutes portraying majestic mountains and dragon-filled skies of ancient China.",
    "Funky slap bass grooves making you envision cool sunglasses-wearing animals strutting their stuff.",
    "Crisp triangle chimes painting images of sparkling icicles in a glistening winter wonderland.",
    "Vibrant tambourine rhythms, beckoning to join a carnival with masks, feathers, and endless joy.",
    "Dulcet tones of a lyre transporting kids to ancient Greece, with heroes and mythical creatures aplenty.",
    "A rousing bagpipe melody leading a parade of knights and castles in the green Scottish highlands.",
    "Giggly xylophone notes bouncing around, like colorful balloons rising into a bright blue sky.",
    "Chirping ukulele paired with soft hand claps, evoking feelings of a cozy campfire singalong."
]
