emoji_descriptions = [
    ("🍕", "A slice of cheesy pizza with pepperoni toppings"),
    # ("🦄", "A magical white unicorn with a twisted horn"),
    ("🌈", "A colorful rainbow arching across a blue sky"),
    ("🍦", "A creamy swirl of soft serve ice cream on a cone"),
    # ("🐱", "A cute kitty cat face with whiskers"),
    ("👻", "A playful white ghost with its tongue sticking out"),
    ("🦖", "A mighty green T-rex dinosaur standing tall"),
    ("🍩", "A round, delicious donut with pink frosting and sprinkles"),
    ("🎈", "A floating red balloon tied with a string"),
    # ("🍭", "A swirly multi-colored lollipop on a stick"),
    ("🎂", "A birthday cake topped with candles and frosting"),
    ("🎁", "A wrapped gift box tied with a big red bow"),
    ("🦋", "A graceful butterfly with vibrant blue wings"),
    ("🐶", "A smiling dog's face with floppy ears"),
    ("🚀", "A silver rocket ship blasting off into space"),
    ("🌟", "A shimmering golden star twinkling in the night"),
    ("🌍", "A representation of our blue and green Earth"),
    ("🍉", "A juicy slice of watermelon with black seeds"),
    ("🦈", "A fierce blue shark with sharp teeth"),
    ("🍫", "A bar of chocolate with a bite taken out of it"),
    ("🎃", "A carved orange pumpkin lantern for Halloween"),
    ("🐰", "A fluffy white rabbit with large, perky ears"),
    # ("🍓", "A ripe red strawberry with green leaves on top"),
    ("🚗", "A shiny red car zooming down the road"),
    ("🎀", "A cute pink bowtie perfect for a gift or hair"),
    ("🍔", "A juicy hamburger with lettuce, cheese, and a beef patty"),
    ("🦩", "A pink flamingo standing on one leg"),
    ("🌺", "A beautiful pink hibiscus flower in full bloom"),
    ("🦙", "A fuzzy brown llama with a curious expression"),
    ("🍪", "A golden brown cookie with chocolate chips"),
    ("🍓", "A plump red strawberry freshly picked from the garden"),
    ("🎨", "A painter's palette with blobs of colorful paint"),
    ("🧁", "A cupcake with creamy frosting and a cherry on top"),
    ("🤖", "A metallic robot with glowing eyes and gears"),
    ("👽", "A green alien with big black eyes from outer space"),
    ("🦍", "A powerful black gorilla pounding its chest"),
    ("🍋", "A bright yellow lemon ready to be squeezed"),
    ("🐺", "A wild gray wolf howling at the moon"),
    ("🌙", "A slender crescent moon shining in the night"),
    ("🍍", "A prickly pineapple with green leaves on top"),
    ("🐉", "A fierce green dragon with wings spread wide"),
    ("🌼", "A bright yellow daisy flower blooming under the sun"),
    ("🦓", "A black and white striped zebra standing still"),
    ("🍟", "A box of crispy golden french fries ready to eat"),
    ("🐠", "A colorful fish swimming in clear blue water"),
    ("🌻", "A tall sunflower with bright yellow petals"),
    ("🍬", "A sweet candy wrapped in a shiny wrapper"),
    ("🧸", "A cuddly teddy bear with soft brown fur"),
    ("🍇", "A bunch of juicy purple grapes hanging together"),
    ("🦜", "A colorful parrot with vibrant feathers perched on a branch"),
    # ('🎁', 'A wrapped gift box with a ribbon, used for birthdays or holidays.'),
    ('🍎', 'A bright red apple with a green leaf on top.'),
    ('🌞', 'A sun with a smiling face, representing the warmth and happiness of a sunny day.'),
    # ('🐱', 'A cat face, looking straight ahead with whiskers and pointy ears.'),
    ('🌲', 'A tall green pine tree, often found in forests.'),
    ('🍦', 'A soft serve ice cream cone, usually vanilla, with a swirl on top.'),
    ('🌈', 'A semi-circle of colors, representing a rainbow in the sky after rain.'),
    ('🦋', 'A butterfly with spread wings, showing its colorful patterns.'),
    # ('⭐', 'A five-point star, often used to represent something shining or special.'),
    ('🍪', 'A round, brown cookie with chocolate chips.'),
    # ("😀", "A grinning face with large eyes and a broad smile, showcasing its teeth."),
    ("🦄", "A mythical unicorn with a spiraled horn on its forehead, representing fantasy and magic."),
    ("🍕", "A delicious slice of pizza with melted cheese and toppings, representing a popular snack."),
    ("👻", "A friendly-looking ghost, with a playful tongue out, representing the fun side of spooky."),
    ("🤖", "A metallic robot face with squared eyes and a straight-line mouth, representing technology."),
    ("🐱", "A cute cat face with pointy ears and whiskers, representing a common household pet."),
    ("🦖", "A fearsome T-rex dinosaur, representing prehistoric creatures and adventures."),
    ("🎃", "A carved pumpkin with a spooky face, representing Halloween and its festivities."),
    # ("🌈", "A colorful arc representing a rainbow, often associated with hope and joy."),
    ("🚀", "A soaring rocket, representing space travel and exploration."),
    ("🍦", "A soft-serve ice cream in a cone, representing a delicious dessert."),
    # ("🦈", "A menacing shark, representing the mysterious and sometimes scary creatures of the deep."),
    ("🌟", "A bright five-point star, representing shining, excellence, or a wish."),
    ("🎁", "A wrapped gift box with a ribbon, representing birthdays and surprises."),
    # ("🎈", "An inflated balloon tied at the bottom, representing celebrations and parties."),
    ("🍪", "A round cookie with chocolate chips, representing a tasty treat."),
    # ("🐶", "A cheerful dog face, representing a loyal companion."),
    ("🍭", "A colorful swirly lollipop, representing sweet candies and treats."),
    ("👾", "A purple space-invader alien, representing video games and extraterrestrial beings.")
]


# note some below are wrong

emoji_descriptions2 = [
    ("😀", "A grinning face showing white teeth without eyes."),
    ("😃", "A grinning face with big eyes and toothy smile."),
    ("😄", "A smiling face with open mouth and smiling eyes."),
    ("😁", "A beaming face with smiling eyes, showing white teeth."),
    ("😆", "A laughing face with squinting eyes and big open mouth."),
    ("😅", "A grinning face with sweat, indicating exertion or relief."),
    ("😂", "A face with tears of joy, laughing very hard."),
    ("🤣", "A face tilted sideways with tears of joy."),
    ("😊", "A smiling face with squinting eyes."),
    ("😇", "A smiling face with halo, representing an angel."),
    ("🙂", "A slightly smiling face."),
    ("🙃", "An upside-down face."),
    ("😉", "A winking face."),
    ("😌", "A relieved face."),
    ("😍", "A face with heart-shaped eyes, indicating love or admiration."),
    ("🥰", "A face with smiling eyes and three hearts floating around."),
    ("😘", "A face blowing a kiss with a heart leaving the mouth."),
    ("😋", "A face savoring delicious food."),
    ("😛", "A face sticking out its tongue."),
    ("😜", "A winking face sticking out its tongue."),
    ("🤪", "A zany face with one big eye and one small eye."),
    ("😝", "A face with squinting eyes sticking out its tongue."),
    ("🤑", "A face with dollar signs for eyes and a green tongue."),
    ("🤗", "A face with open hands, indicating a hug."),
    ("🤔", "A face with a raised eyebrow and chin resting on hand, thinking."),
    ("🤐", "A face with a zipper mouth, indicating silence."),
    ("🤡", "A clown face."),
    ("🥳", "A partying face with a party hat and confetti."),
    ("😎", "A cool face with sunglasses."),
    ("🤓", "A nerd face with thick glasses."),
    ("🧐", "A face with a monocle, inspecting or observing."),
    ("😕", "A confused face."),
    ("😟", "A worried face."),
    ("🙁", "A slightly frowning face."),
    ("☹️", "A frowning face."),
    ("😮", "A face with open mouth, surprised or in awe."),
    ("😯", "A hushed face with wide open eyes."),
    ("😲", "An astonished face with wide open eyes and open mouth."),
    ("😳", "A flushed face, embarrassed or in shock."),
    ("🥺", "A pleading face with big watery eyes."),
    ("😦", "A frowning face with open mouth."),
    ("😧", "A face with open mouth and cold sweat, distressed."),
    ("😨", "A fearful face."),
    ("😰", "A face with open mouth and cold sweat, anxious."),
    ("😥", "A disappointed but relieved face."),
    ("😢", "A crying face, shedding a tear."),
    ("😭", "A loudly crying face, shedding multiple tears."),
    ("😱", "A face screaming in fear."),
    ("😖", "A confounded face."),
    ("😣", "A persevering face."),
    ("😞", "A disappointed face."),
    ("😓", "A face with cold sweat."),
    ("😩", "A weary face."),
    ("😫", "A tired face."),
    ("🥱", "A yawning face."),
    ("😤", "A face with steam coming out of its nose, frustrated."),
    ("😡", "A pouting face, very angry."),
    ("😠", "An angry face."),
    ("🤬", "A face with symbols over the mouth, swearing."),
    ("😈", "A smiling face with horns, a happy devil."),
    ("👿", "An angry face with horns, an angry devil."),
    ("💀", "A skull."),
    ("☠️", "A skull and crossbones."),
    ("👻", "A ghost."),
    ("👽", "An alien."),
    ("🤖", "A robot face."),
    ("😺", "A grinning cat face."),
    ("😸", "A grinning cat face with smiling eyes."),
    ("😹", "A cat face with tears of joy."),
    ("😻", "A cat face with heart-shaped eyes."),
    ("😼", "A cat face with a smirk."),
    ("😽", "A kissing cat face."),
    ("🙀", "A weary cat face."),
    ("😿", "A crying cat face."),
    ("😾", "A pouting cat face."),
    ("🙈", "A monkey covering its eyes."),
    ("🙉", "A monkey covering its ears."),
    ("🙊", "A monkey covering its mouth."),
    ("🐵", "A monkey face."),
    ("🐶", "A dog face."),
    ("🐱", "A cat face."),
    ("🐭", "A mouse face."),
    ("🐰", "A rabbit face."),
    ("🦄", "A unicorn face."),
    ("🦁", "A lion face."),
    ("🐸", "A frog face."),
    ("🐷", "A pig face."),
    ("🐻", "A bear face."),
    ("🐼", "A panda face."),
    ("🐨", "A koala face."),
    ("🐯", "A tiger face."),
    ("🦊", "A fox face."),
    ("🦓", "A zebra face."),
    ("🦒", "A giraffe face."),
    ("🦌", "A deer face."),
    ("🐮", "A cow face."),
    ("🐧", "A penguin."),
    ("🐦", "A bird."),
    ("🐤", "A baby chick."),
    ("🐔", "A chicken."),
    ("🐣", "A hatching chick."),
    ("🐢", "A turtle."),
    ("🐍", "A snake."),
    ("🦎", "A lizard."),
    ("🦖", "A T-Rex dinosaur."),
    ("🦕", "A sauropod dinosaur."),
    ("🦈", "A shark."),
    ("🦉", "An owl."),
    ("🦤", "A dodo bird."),
    ("🦔", "A hedgehog."),
    ("🦦", "An otter."),
    ("🦩", "A flamingo."),
    ("🦥", "A sloth."),
    ("🦨", "A skunk."),
    ("🦪", "An oyster."),
    ("🍕", "A slice of pizza."),
    ("🍔", "A hamburger."),
    ("🍟", "French fries."),
    ("🍦", "An ice cream cone."),
    ("🍎", "A red apple."),
    ("🍉", "A slice of watermelon."),
    ("🍇", "Grapes."),
    ("🍓", "A strawberry."),
    ("🍍", "A pineapple."),
    ("🍭", "A lollipop."),
    ("🍩", "A doughnut."),
    ("🎂", "A birthday cake."),
    ("🎈", "A balloon."),
    ("🎉", "A party popper with confetti."),
    ("🎁", "A wrapped gift."),
    ("🚂", "A locomotive."),
    ("🚀", "A rocket."),
    ("🛸", "A flying saucer."),
    ("🚁", "A helicopter."),
    ("✈️", "An airplane."),
    ("🚗", "A car."),
    ("🚌", "A bus."),
    ("🚓", "A police car."),
    ("🚑", "An ambulance."),
    ("🚒", "A fire engine."),
    ("🚚", "A delivery truck."),
    ("🛴", "A scooter."),
    ("🚲", "A bicycle."),
    ("🚢", "A ship."),
    ("🛏️", "A bed."),
    ("⌚", "A watch."),
    ("📱", "A mobile phone."),
    ("📺", "A television."),
    ("💻", "A laptop computer."),
    ("⌨️", "A keyboard."),
    ("🕹️", "A joystick."),
    ("🎮", "A video game controller."),
    ("🎥", "A movie camera."),
    ("📷", "A camera."),
    ("📸", "A camera with flash."),
    ("🔦", "A flashlight."),
    ("💡", "A light bulb."),
    ("📖", "An open book."),
    ("📚", "A stack of books."),
    ("🖍️", "A crayon."),
    ("🎨", "An artist's palette."),
    ("🎤", "A microphone."),
    ("🎧", "Headphones."),
    ("🎼", "A musical score."),
    ("🎹", "A musical keyboard."),
    ("🎸", "A guitar."),
    ("🥁", "A drum with drumsticks."),
    ("🚂", "A steam locomotive."),
    ("🌈", "A rainbow."),
    # ("🌍", "A globe showing Europe and Africa."),
    # ("🌎", "A globe showing the Americas."),
    # ("🌏", "A globe showing Asia and Australia."),
    ("🌞", "A sun with face."),
    ("🌝", "A full moon with face."),
    ("🌛", "A first quarter moon with face."),
    ("🌜", "A last quarter moon with face."),
    ("⭐", "A white medium star."),
    ("🌟", "A glowing star."),
    ("💫", "A dizzy symbol, star with trail."),
    ("✨", "Sparkles."),
    ("🌠", "A shooting star."),
    ("❤️", "A red heart."),
    ("💔", "A broken heart."),
    ("💖", "A sparkling heart."),
    ("💘", "A heart with arrow."),
    ("💝", "A heart with ribbon."),
    ("💌", "A love letter, heart with an envelope."),
    ("💍", "A ring."),
    ("💎", "A gem, diamond."),
    ("🔒", "A locked padlock."),
    ("🔑", "A key."),
    ("🛍️", "Shopping bags."),
    ("💼", "A briefcase."),
    ("👓", "Glasses."),
    ("🕶️", "Dark sunglasses."),
    ("🌂", "A closed umbrella."),
    ("☂️", "An open umbrella."),
    ("👜", "A handbag."),
    ("🎒", "A backpack."),
    ("👟", "A sneaker or athletic shoe."),
    ("👞", "A man's shoe."),
    ("👢", "A woman's boot."),
    ("👠", "A high-heeled shoe."),
    ("👡", "A woman's sandal."),
    ("👙", "A bikini."),
    ("👗", "A dress."),
    ("🧥", "A coat."),
    ("👚", "A blouse."),
    ("👕", "A t-shirt."),
    ("👖", "Blue jeans."),
    ("👔", "A shirt with tie."),
    ("👑", "A crown."),
    ("👒", "A woman's hat."),
    ("🎩", "A top hat."),
    ("⛑️", "A rescue worker's helmet."),
    ("🎓", "A graduation cap."),
    ("🧢", "A billed cap."),
    ("🍼", "A baby bottle."),
    ("🍭", "A lollipop."),
    ("🧸", "A teddy bear."),
    ("🎈", "A balloon."),
    ("🎀", "A ribbon bow."),
    ("🎁", "A wrapped gift."),
    ("🎉", "A party popper."),
    ("🎊", "Confetti ball."),
    ("🎈", "A balloon."),
    ("🎏", "Carp streamer."),
    ("🎀", "A ribbon bow."),
    ("🎁", "A wrapped gift."),
    ("🎉", "A party popper."),
    ("🎊", "A confetti ball."),
    ("🎖️", "A military medal."),
    ("🏆", "A trophy."),
    ("🏅", "A sports medal."),
    ("⚽", "A soccer ball."),
    ("🏀", "A basketball."),
    ("🏈", "An American football."),
    ("⚾", "A baseball."),
    ("🎾", "A tennis ball."),
    ("🏐", "A volleyball."),
    ("🏉", "A rugby football."),
    ("🎱", "An 8-ball from pool."),
    ("🏓", "A ping pong paddle and ball."),
    ("🏸", "A badminton racket and shuttlecock."),
    ("🥅", "A goal net."),
    ("⛳", "A flag in hole, golf."),
    ("🏹", "A bow with arrow."),
    ("🎣", "A fishing pole with fish."),
    ("🎳", "Bowling pins and ball."),
    ("🛷", "A sled."),
    ("🎿", "Skis."),
    ("🛹", "A skateboard."),
    ("🤖", "A robot face."),
    ("👾", "An alien monster, like from video games."),
    ("👻", "A ghost."),
    ("💀", "A skull."),
    ("🎃", "A jack-o-lantern, pumpkin."),
    ("🐉", "A dragon."),
    ("🐲", "A dragon face."),
    ("🦄", "A unicorn face."),
    ("🦕", "A sauropod, dinosaur."),
    ("🦖", "A T-Rex, dinosaur."),
    ("🌱", "A seedling."),
    ("🌲", "An evergreen tree."),
    ("🌳", "A deciduous tree."),
    ("🌴", "A palm tree."),
    ("🌵", "A cactus."),
    ("🌷", "A tulip."),
    ("🌸", "A cherry blossom."),
    ("🌹", "A red rose."),
    ("🍁", "A maple leaf."),
    ("🍂", "Fallen leaves."),
    ("🍃", "A leaf fluttering in the wind."),
    ("❄️", "A snowflake."),
    ("☃️", "A snowman."),
    ("⛄", "A snowman without snow."),
    ("☔", "An umbrella with rain."),
    ("💧", "A droplet."),
    ("🌊", "A wave."),
    ("🍏", "A green apple."),
    ("🍐", "A pear."),
    ("🍑", "A peach."),
    ("🍒", "Cherries."),
    ("🍓", "A strawberry."),
    ("🍅", "A tomato."),
    ("🍆", "An eggplant."),
    ("🥑", "An avocado."),
    ("🥦", "A broccoli."),
    ("🥒", "A cucumber."),
    ("🥕", "A carrot."),
    ("🌽", "An ear of corn."),
    ("🌶️", "A hot pepper."),
    ("🥔", "A potato."),
    ("🍠", "A sweet potato."),
    ("🥐", "A croissant."),
    ("🥖", "A baguette bread."),
    ("🍞", "A loaf of bread."),
    ("🥨", "A pretzel."),
    ("🥞", "Pancakes."),
    ("🍖", "A bone in meat."),
    ("🍗", "A chicken leg."),
    ("🥓", "Bacon."),
    ("🍔", "A hamburger."),
    ("🍟", "French fries."),
    ("🍕", "A slice of pizza."),
    ("🌭", "A hot dog."),
    ("🥪", "A sandwich."),
    ("🍱", "A bento box."),
    ("🍣", "Sushi."),
    ("🍛", "A curry and rice."),
    ("🍜", "A steaming bowl, like noodle."),
    ("🍝", "Spaghetti."),
    ("🍠", "Roasted sweet potato."),
    ("🍢", "Oden."),
    ("🍣", "Sushi."),
    ("🍤", "Fried shrimp."),
    ("🍥", "Fish cake with swirl."),
    ("🍦", "Soft ice cream."),
    ("🍧", "Shaved ice."),
    ("🍨", "Ice cream."),
    ("🍩", "A doughnut."),
    ("🍪", "A cookie."),
    ("🎂", "A birthday cake."),
    ("🍰", "A slice of cake."),
    ("🧁", "A cupcake."),
    ("🥧", "A pie."),
    ("🍫", "A bar of chocolate."),
    ("🍬", "Candies."),
    ("🍭", "A lollipop."),
    ("🍯", "A honey pot."),
    ("🍼", "A baby bottle."),
    ("🥛", "A glass of milk."),
    ("☕", "A cup of coffee."),
    ("🍵", "A cup of tea."),
    ("🍶", "A sake bottle and cup."),
    ("🍺", "A beer mug."),
    ("🍻", "Clinking beer mugs."),
    ("🥂", "Clinking glasses with champagne."),
    ("🍷", "A glass of wine."),
    ("🥃", "A tumbler glass with drink."),
    ("🍸", "A cocktail glass."),
    ("🍹", "A tropical drink."),
    ("🍾", "A bottle of popping champagne."),
    ("🥄", "A spoon."),
    ("🍴", "A fork and knife."),
    ("🍽️", "A plate with fork and knife."),
    ("🔪", "A kitchen knife."),
    ("🏺", "An amphora."),
    # ("🌍", "A globe showing Europe-Africa."),
    # ("🌎", "A globe showing Americas."),
    # ("🌏", "A globe showing Asia-Australia."),
    # ("🌐", "A globe with meridians."),
    ("🗺️", "A world map."),
    ("🗾", "A map of Japan."),
    ("🏔️", "A snow-capped mountain."),
    ("⛰️", "A mountain."),
    ("🌋", "A volcano."),
    ("🗻", "Mount Fuji."),
    ("🏕️", "A camping site."),
    ("🏖️", "A beach with umbrella."),
    ("🏜️", "A desert."),
    ("🏝️", "A desert island."),
    ("🏞️", "A national park."),
    ("🏟️", "A stadium."),
    ("🏛️", "A classical building."),
    ("🏗️", "A building construction."),
    ("🏘️", "Houses."),
    ("🏙️", "A cityscape."),
    ("🏚️", "A derelict house."),
    ("🏠", "A house."),
    ("🏡", "A house with garden."),
    ("🏢", "An office building."),
    ("🏣", "A Japanese post office."),
    ("🏤", "A European post office."),
    ("🏥", "A hospital."),
    ("🏦", "A bank."),
    ("🏨", "A hotel."),
    ("🏩", "A love hotel."),
    ("🏪", "A convenience store."),
    ("🏫", "A school."),
    ("🏬", "A department store."),
    ("🏭", "A factory."),
    ("🏯", "A Japanese castle."),
    ("🏰", "A European castle."),
    ("💒", "A wedding chapel."),
    ("🗼", "Tokyo tower."),
    ("🗽", "Statue of Liberty."),
    ("⛪", "A church."),
    ("🕌", "A mosque."),
    ("🕍", "A synagogue."),
    ("⛩️", "A Shinto shrine."),
    ("🕋", "Kaaba."),
    ("⛺", "A tent."),
    ("🌁", "Foggy city."),
    ("🌃", "Night with stars."),
    ("🌄", "Sunrise over mountains."),
    ("🌅", "Sunrise."),
    ("🌆", "Cityscape at dusk."),
    ("🌇", "Sunset over city."),
    ("🌉", "Bridge at night."),
    ("🌌", "Milky Way."),
    ("🎠", "A carousel horse."),
    ("🎡", "A ferris wheel."),
    ("🎢", "A roller coaster."),
    ("🎣", "Fishing pole."),
    ("🎤", "A microphone."),
    ("🎥", "A movie camera."),
    ("🎦", "A cinema."),
    ("🎧", "Headphones."),
    ("🎨", "An artist palette."),
    ("🎩", "A top hat."),
    ("🎪", "A circus tent."),
    ("🎫", "A ticket."),
    ("🎬", "A clapper board."),
    ("🎭", "Performing arts."),
    ("🎮", "A video game controller."),
    ("🎯", "Direct hit."),
    ("🎰", "A slot machine."),
    ("🎱", "A billiards ball."),
    ("🎲", "A pair of dice."),
    ("🎳", "Bowling."),
    ("🎴", "Japanese playing cards."),
    ("🎵", "A musical note."),
    ("🎶", "Multiple musical notes."),
    ("🎷", "A saxophone."),
    ("🎸", "A guitar."),
    ("🎹", "A musical keyboard."),
    ("🎺", "A trumpet."),
    ("🎻", "A violin."),
    ("🎼", "A musical score."),
    ("🎽", "A running shirt."),
    ("🎾", "A tennis racket and ball."),
    ("🎿", "Skis."),
    ("🏀", "A basketball."),
    ("🏁", "A chequered flag."),
    ("🏂", "A snowboarder."),
    ("🏃", "A person running."),
    ("🏄", "A person surfing."),
    ("🏅", "A sports medal."),
    ("🏆", "A trophy."),
    ("🏇", "A horse racing."),
    ("🏈", "An American football."),
    ("🏉", "A rugby football."),
    ("🏊", "A person swimming."),
    ("🏋️", "A person lifting weights."),
    ("🏌️", "A person golfing."),
    ("🏍️", "A motorbike."),
    ("🏎️", "A racing car."),
    ("🏏", "A cricket game."),
    ("🏐", "A volleyball."),
    ("🏑", "A field hockey game."),
    ("🏒", "An ice hockey game."),
    ("🏓", "A ping pong game."),
    ("🏔️", "A snow-capped mountain."),
    ("🏕️", "A camping site."),
    ("🏖️", "A beach with umbrella."),
    ("🏗️", "Building construction."),
    ("🏘️", "Houses."),
    ("🏙️", "A cityscape."),
    ("🏚️", "A derelict house."),
    ("🏛️", "A classical building."),
    ("🏜️", "A desert."),
    ("🏝️", "A desert island."),
    ("🏞️", "A national park."),
    ("🏟️", "A stadium."),
    ("🏠", "A house."),
    ("🏡", "A house with garden."),
    ("🏢", "An office building."),
    ("🏣", "A Japanese post office."),
    ("🏤", "A European post office."),
    ("🏥", "A hospital."),
    ("🏦", "A bank."),
    ("🏨", "A hotel."),
    ("🏩", "A love hotel."),
    ("🏪", "A convenience store."),
    ("🏫", "A school."),
    ("🏬", "A department store."),
    ("🏭", "A factory."),
    ("🏮", "A red paper lantern."),
    ("🏯", "A Japanese castle."),
    ("🏰", "A European castle."),
    ("🏳️", "A white flag."),
    ("🏴", "A black flag."),
    ("🏵️", "A rosette."),
    ("🏶", "A black small square."),
    ("🏷️", "A label."),
    ("🏸", "A badminton racket and shuttlecock."),
    ("🏹", "A bow and arrow."),
    ("🏺", "An amphora."),
    # ("🏻", "Light skin tone modifier."),
    # ("🏼", "Medium-light skin tone modifier."),
    # ("🏽", "Medium skin tone modifier."),
    # ("🏾", "Medium-dark skin tone modifier."),
    # ("🏿", "Dark skin tone modifier."),
    ("🐀", "A rat."),
    ("🐁", "A mouse."),
    ("🐂", "An ox."),
    ("🐃", "A water buffalo."),
    ("🐄", "A cow."),
    ("🐅", "A tiger."),
    ("🐆", "A leopard."),
    ("🐇", "A rabbit."),
    ("🐈", "A cat."),
    ("🐉", "A dragon."),
    ("🐊", "A crocodile."),
    ("🐋", "A whale."),
    ("🐌", "A snail."),
    ("🐍", "A snake."),
    ("🐎", "A horse."),
    ("🐏", "A ram."),
    ("🐐", "A goat."),
    ("🐑", "A sheep."),
    ("🐒", "A monkey."),
    ("🐓", "A rooster."),
    ("🐔", "A chicken."),
    ("🐕", "A dog."),
    ("🐖", "A pig."),
    ("🐗", "A wild boar."),
    ("🐘", "An elephant."),
    ("🐙", "An octopus."),
    ("🐚", "A seashell."),
    ("🐛", "A bug."),
    ("🐜", "An ant."),
    ("🐝", "A honeybee."),
    ("🐞", "A ladybug."),
    ("🐟", "A fish."),
    ("🐠", "A tropical fish."),
    ("🐡", "A blowfish."),
    ("🐢", "A turtle."),
    ("🐣", "A chick hatching from an egg."),
    ("🐤", "A baby chick."),
    ("🐥", "A front-facing baby chick."),
    ("🐦", "A bird."),
    ("🐧", "A penguin."),
    ("🐨", "A koala."),
    ("🐩", "A poodle."),
    ("🐪", "A camel."),
    ("🐫", "A two-hump camel."),
    ("🐬", "A dolphin."),
    ("🐭", "A mouse face."),
    ("🐮", "A cow face."),
    ("🐯", "A tiger face."),
    ("🐰", "A rabbit face."),
    ("🐱", "A cat face."),
    ("🐲", "A dragon face."),
    ("🐳", "A spouting whale."),
    ("🐴", "A horse face."),
    ("🐵", "A monkey face."),
    ("🐶", "A dog face."),
    ("🐷", "A pig face."),
    ("🐸", "A frog face."),
    ("🐹", "A hamster face."),
    ("🐺", "A wolf face."),
    ("🐻", "A bear face."),
    ("🐼", "A panda face."),
    ("🐽", "A pig nose."),
    ("🐾", "Paw prints."),
    ("🐿️", "A chipmunk."),
    ("👀", "A pair of eyes."),
    ("👁️", "An eye."),
    ("👂", "An ear."),
    ("👃", "A nose."),
    ("👄", "Lips."),
    ("👅", "A tongue."),
    ("👆", "A pointing up hand."),
    # ("👇", "A pointing down hand."),
    # ("👈", "A pointing left hand."),
    # ("👉", "A pointing right hand."),
    ("👊", "A fist."),
    ("👋", "A waving hand."),
    ("👌", "An OK hand."),
    ("👍", "A thumbs up."),
    ("👎", "A thumbs down."),
    ("👏", "Clapping hands."),
    ("👐", "Open hands."),
    ("👑", "A crown."),
    ("👒", "A woman's hat."),
    ("👓", "Glasses."),
    ("👔", "A necktie."),
    ("👕", "A t-shirt."),
    ("👖", "Jeans."),
    ("👗", "A dress."),
    ("👘", "A kimono."),
    ("👙", "A bikini."),
    ("👚", "A woman's blouse."),
    ("👛", "A purse."),
    ("👜", "A handbag."),
    ("👝", "A clutch bag."),
    ("👞", "A man's shoe."),
    ("👟", "A running shoe."),
    ("👠", "A high-heeled shoe."),
    ("👡", "A woman's sandal."),
    ("👢", "A woman's boot."),
    ("👣", "Footprints."),
    # ("👤", "A silhouette of a person."),
    # ("👥", "A silhouette of two people."),
    ("👦", "A boy."),
    ("👧", "A girl."),
    ("👨", "A man."),
    ("👩", "A woman."),
    ("👪", "A family."),
    ("👫", "A man and a woman."),
    ("👬", "Two men."),
    ("👭", "Two women."),
    ("👮", "A police officer."),
    ("👯", "People with bunny ears."),
    ("👰", "A bride."),
    ("👱", "A person with blond hair."),
    ("👲", "A man with a gua pi mao."),
    ("👳", "A person wearing a turban."),
    ("👴", "An old man."),
    ("👵", "An old woman."),
    ("👶", "A baby."),
    ("👷", "A construction worker."),
    ("👸", "A princess."),
    ("👹", "A Japanese ogre."),
    ("👺", "A Japanese goblin."),
    ("👻", "A ghost."),
    ("👼", "An angel."),
    ("👽", "An alien."),
    ("👾", "An alien monster."),
    ("👿", "An imp."),
    ("💀", "A skull."),
    ("💁", "A person tipping hand."),
    ("💂", "A guardsman."),
    ("💃", "A dancer."),
    ("💄", "Lipstick."),
    ("💅", "Nail polish."),
    ("💆", "A person getting a massage."),
    ("💇", "A person getting a haircut."),
    ("💈", "A barbershop pole."),
    ("💉", "A syringe."),
    ("💊", "A pill."),
    ("💋", "Kiss mark."),
    ("💌", "A love letter."),
    ("💍", "A ring."),
    ("💎", "A gemstone."),
    ("💏", "A couple kissing."),
    ("💐", "A bouquet."),
    ("💑", "A couple with heart."),
    ("💒", "A wedding chapel."),
    ("💓", "A beating heart."),
    ("💔", "A broken heart."),
    ("💕", "Two hearts."),
    ("💖", "A sparkling heart."),
    ("💗", "A growing heart."),
    ("💘", "A heart with arrow."),
    # ("💙", "A blue heart."),
    # ("💚", "A green heart."),
    # ("💛", "A yellow heart."),
    # ("💜", "A purple heart."),
    # ("💝", "A heart with ribbon."),
    # ("💞", "Revolving hearts."),
    # ("💟", "A heart decoration."),
    ("💠", "A diamond with a dot."),
    ("💡", "A light bulb."),
    ("💢", "An anger symbol."),
    ("💣", "A bomb."),
    ("💤", "Sleeping symbol (Zzz)."),
    ("💥", "A collision."),
    ("💦", "Sweat droplets."),
    ("💧", "A droplet."),
    ("💨", "A dash."),
    ("💩", "A pile of poo."),
    ("💪", "A flexed bicep."),
    ("💫", "Dizzy."),
    # ("💬", "A speech bubble."),
    # ("💭", "A thought bubble."),
    ("💮", "A white flower."),
    # ("💯", "A hundred points symbol."),
    ("💰", "A money bag."),
    ("💱", "Currency exchange."),
    ("💲", "A heavy dollar sign."),
    ("💳", "A credit card."),
    ("💴", "A yen banknote."),
    ("💵", "A dollar banknote."),
    ("💶", "A euro banknote."),
    ("💷", "A pound banknote."),
    ("💸", "Flying money."),
    ("💹", "A rising stock chart."),
    ("💺", "A seat."),
    ("💻", "A laptop."),
    ("💼", "A briefcase."),
    # ("💽", "A computer disk."),
    # ("💾", "A floppy disk."),
    # ("💿", "A CD."),
    # ("📀", "A DVD."),
    # ("📁", "A file folder."),
    # ("📂", "An open file folder."),
    # ("📃", "A page with a curl."),
    # ("📄", "A page."),
    # ("📅", "A calendar."),
    # ("📆", "A tear-off calendar."),
    # ("📇", "A card index."),
    # ("📈", "A rising graph."),
    # ("📉", "A falling graph."),
    # ("📊", "A bar chart."),
    ("📋", "A clipboard."),
    ("📌", "A pushpin."),
    ("📍", "A round pushpin."),
    ("📎", "A paperclip."),
    ("📏", "A straight ruler."),
    ("📐", "A triangular ruler."),
    ("📑", "Bookmarks."),
    ("📒", "A ledger."),
    # ("📓", "A notebook."),
    # ("📔", "A notebook with a decorative cover."),
    # ("📕", "A closed book."),
    # ("📖", "An open book."),
    # ("📗", "A green book."),
    # ("📘", "A blue book."),
    # ("📙", "An orange book."),
    ("📚", "Books."),
    ("📛", "A name badge."),
    ("📜", "A scroll."),
    ("📝", "A memo."),
    ("📞", "A telephone receiver."),
    ("📟", "A pager."),
    ("📠", "A fax machine."),
    ("📡", "A satellite antenna."),
    ("📢", "A loudspeaker."),
    ("📣", "A megaphone."),
    # ("📤", "Outbox tray."),
    # ("📥", "Inbox tray."),
    ("📦", "A package."),
    # ("📧", "An e-mail."),
    # ("📨", "An incoming envelope."),
    # ("📩", "An envelope with an arrow."),
    # ("📪", "A closed mailbox with lowered flag."),
    # ("📫", "A closed mailbox with raised flag."),
    # ("📬", "An open mailbox with letters."),
    # ("📭", "An open mailbox with lowered flag."),
    ("📮", "A postbox."),
    ("📯", "A postal horn."),
    ("📰", "A newspaper."),
    # ("📱", "A mobile phone."),
    # ("📲", "A mobile phone with an arrow."),
    # ("📳", "A vibration mode."),
    # ("📴", "A mobile phone off."),
    ("📵", "No mobile phones."),
    # ("📶", "A mobile phone signal."),
    ("📷", "A camera."),
    # ("📸", "A camera with flash."),
    # ("📹", "A video camera."),
    ("📺", "A television."),
    ("📻", "A radio."),
    # ("📼", "A videocassette."),
    ("📽️", "A film projector."),
    # ("📿", "A prayer beads."),
    # ("🔀", "A shuffle tracks button."),
    # ("🔁", "A repeat button."),
    # ("🔂", "A repeat single button."),
    # ("🔃", "A clockwise vertical arrows."),
    # ("🔄", "A counterclockwise arrows button."),
    # ("🔅", "A low brightness button."),
    # ("🔆", "A high brightness button."),
    # ("🔇", "A muted speaker."),
    # ("🔈", "A speaker low volume."),
    # ("🔉", "A speaker medium volume."),
    # ("🔊", "A speaker high volume."),
    # ("🔋", "A battery."),
    # ("🔌", "An electric plug."),
    # ("🔍", "A magnifying glass tilted left."),
    # ("🔎", "A magnifying glass tilted right."),
    # ("🔏", "A locked with pen."),
    # ("🔐", "A locked with key."),
    # ("🔑", "A key."),
    # ("🔒", "A locked."),
    # ("🔓", "An unlocked."),
    # ("🔔", "A bell."),
    # ("🔕", "A bell with a slash."),
    # ("🔖", "A bookmark."),
    # ("🔗", "A link."),
    # ("🔘", "A radio button."),
    # ("🔙", "A back arrow."),
    # ("🔚", "An end arrow."),
    # ("🔛", "An on arrow."),
    # ("🔜", "A soon arrow."),
    # ("🔝", "A top arrow."),
    # ("🔞", "An eighteen plus."),
    # ("🔟", "A keycap ten."),
    # ("🔠", "An input latin uppercase."),
    # ("🔡", "An input latin lowercase."),
    # ("🔢", "An input numbers."),
    # ("🔣", "An input symbols."),
    # ("🔤", "An input latin letters."),
    ("🔥", "A fire."),
    ("🔦", "A flashlight."),
    ("🔧", "A wrench."),
    ("🔨", "A hammer."),
    ("🔩", "A nut and bolt."),
    ("🔪", "A kitchen knife."),
    ("🔫", "A pistol."),
    ("🔬", "A microscope."),
    ("🔭", "A telescope."),
    ("🔮", "A crystal ball."),
    ("🔯", "A six-pointed star with a dot in the center."),
    ("🔰", "A Japanese symbol for beginner."),
    ("🔱", "A trident emblem."),
    # ("🔲", "A black square button."),
    # ("🔳", "A white square button."),
    # ("🔴", "A red circle."),
    # ("🔵", "A blue circle."),
    # ("🔶", "A large orange diamond."),
    # ("🔷", "A large blue diamond."),
    # ("🔸", "A small orange diamond."),
    # ("🔹", "A small blue diamond."),
    # ("🔺", "A red triangle pointed up."),
    # ("🔻", "A red triangle pointed down."),
    # ("🔼", "A triangle pointed up."),
    # ("🔽", "A triangle pointed down."),
    # ("🕀", "A joker."),
    # ("🕁", "A mahjong red dragon."),
    # ("🕂", "A black joker."),
    # ("🕃", "A playing card ace of spades."),
    # ("🕄", "A playing card ace of hearts."),
    # ("🕅", "A playing card ace of diamonds."),
    # ("🕆", "A playing card ace of clubs."),
    # ("🕇", "A playing card black joker."),
    # ("🕈", "A playing card red joker."),
    # ("🕉️", "An om."),
    ("🕊️", "A dove."),
    ("🕋", "A kaaba."),
    ("🕌", "A mosque."),
    ("🕍", "A synagogue."),
    ("🕎", "A menorah."),
    # ("🕏", "A clockwise vertical arrows."),
    # ("🕐", "A clock face one o'clock."),
    # ("🕑", "A clock face two o'clock."),
    # ("🕒", "A clock face three o'clock."),
    # ("🕓", "A clock face four o'clock."),
    # ("🕔", "A clock face five o'clock."),
    # ("🕕", "A clock face six o'clock."),
    # ("🕖", "A clock face seven o'clock."),
    # ("🕗", "A clock face eight o'clock."),
    # ("🕘", "A clock face nine o'clock."),
    # ("🕙", "A clock face ten o'clock."),
    # ("🕚", "A clock face eleven o'clock."),
    # ("🕛", "A clock face twelve o'clock."),
    # ("🕜", "A clock face one-thirty."),
    # ("🕝", "A clock face two-thirty."),
    # ("🕞", "A clock face three-thirty."),
    # ("🕟", "A clock face four-thirty."),
    # ("🕠", "A clock face five-thirty."),
    # ("🕡", "A clock face six-thirty."),
    # ("🕢", "A clock face seven-thirty."),
    # ("🕣", "A clock face eight-thirty."),
    # ("🕤", "A clock face nine-thirty."),
    # ("🕥", "A clock face ten-thirty."),
    # ("🕦", "A clock face eleven-thirty."),
    # ("🕧", "A clock face twelve-thirty."),
    # ("🕨", "A clock face pointing to the hour."),
    # ("🕩", "A clock face pointing to the half hour."),
    # ("🕪", "A clock face pointing to the quarter hour."),
    # ("🕫", "A clock face pointing to three-quarters."),
    # ("🕬", "A clock face with a line through the middle."),
    # ("🕭", "A clock face without any hands."),
    # ("🕮", "A book with a bookmark."),
    ("🕯️", "A candle."),
    ("🕰️", "A mantelpiece clock."),
    # ("🕱", "A black hourglass."),
    # ("🕲", "A white hourglass."),
    # ("🕳️", "A hole."),
    # ("🕴️", "A man in a suit, levitating."),
    ("🕵️", "A detective."),
    ("🕶️", "Sunglasses."),
    ("🕷️", "A spider."),
    ("🕸️", "A spider web."),
    ("🕹️", "A joystick."),
    ("🕺", "A man dancing."),
    # ("🕻", "A leftwards arrow above a backwards phone."),
    # ("🕼", "A rightwards arrow above a phone."),
    # ("🕽", "A white flag with a horizontal middle black stripe."),
    # ("🕾", "A black flag with a horizontal middle white stripe."),
    # ("🕿", "A closed mailbox with an X."),
    # ("🖀", "A black pen with a white ink."),
    # ("🖁", "A white pen with a black ink."),
    # ("🖂", "A memo with a pencil."),
    # ("🖃", "A memo with a pen."),
    # ("🖄", "A ballot box with a check."),
    # ("🖅", "A ballot box with a cross."),
    # ("🖆", "A ballot box with a ballot."),
    # ("🖇️", "Linked paperclips."),
    # ("🖈", "An abacus."),
    # ("🖉", "A magnifying glass over an open book."),
    ("🖊️", "A pen."),
    ("🖋️", "A fountain pen."),
    ("🖌️", "A paintbrush."),
    ("🖍️", "A crayon."),
    # ("🖎", "A pencil with a line."),
    # ("🖏", "A pencil with an X."),
    # ("🖐️", "A hand with fingers splayed."),
    # ("🖑", "A hand with fingers splayed and thumb extended."),
    # ("🖒", "A thumbs up."),
    # ("🖓", "A thumbs down."),
    # ("🖔", "A white up pointing hand."),
    # ("🖕", "A middle finger."),
    ("🖖", "A Vulcan salute."),
    # ("🖗", "A white down pointing hand."),
    # ("🖘", "A sign of the horns."),
    # ("🖙", "A hand with first and second fingers crossed."),
    # ("🖚", "A raised hand with part between middle and ring fingers."),
    # ("🖛", "A hand with index and middle fingers crossed."),
    # ("🖜", "A hand with index and little fingers."),
    # ("🖝", "A hand with thumb and index finger extended."),
    # ("🖞", "A hand with thumb and little finger extended."),
    # ("🖟", "A hand with thumb and middle finger extended."),
    # ("🖠", "A hand with thumb and ring finger extended."),
    # ("🖡", "A hand with all fingers and thumb held together."),
    # ("🖢", "A pinching hand."),
    # ("🖣", "A call me hand."),
    # ("🖤", "A black heart."),
    # ("🖥️", "A desktop computer."),
    # ("🖦", "A printer."),
    # ("🖧", "A keyboard."),
    # ("🖨️", "A three button mouse."),
    # ("🖩", "A two-button mouse."),
    # ("🖪", "A trackball."),
    # ("🖫", "An old personal computer."),
    # ("🖬", "A floppy disk."),
    # ("🖭", "A compact disc."),
    # ("🖮", "An optical disc."),
    # ("🖯", "A dvd."),
    # ("🖰️", "A mouse."),
    ("🖱️", "A mouse with three buttons."),
    # ("🖲️", "A trackball."),
    # ("🖳", "A black hard drive."),
    # ("🖴", "A white hard drive."),
    # ("🖵", "A floppy disk."),
    # ("🖶", "A printer."),
    # ("🖷", "A strikethrough keyboard."),
    # ("🖸", "A keyboard and mouse."),
    # ("🖹", "A three button mouse."),
    # ("🖺", "A two-button mouse."),
    # ("🖻", "A trackball."),
    ("🖼️", "A framed picture."),
    # ("🖽", "A black floppy disk."),
    # ("🖾", "A white floppy disk."),
    # ("🖿", "A compact disc."),
    # ("🗀", "An optical disc."),
    # ("🗁", "A dvd."),
    ("🗂️", "Card index dividers."),
    ("🗃️", "A card file box."),
    ("🗄️", "A file cabinet."),
    # ("🗅", "A file folder."),
    # ("🗆", "An open file folder."),
    # ("🗇", "A card index."),
    # ("🗈", "A rolodex."),
    # ("🗉", "A spiral note pad."),
    # ("🗊", "A spiral calendar."),
    # ("🗋", "A desktop window."),
    # ("🗌", "A desktop computer and keyboard."),
    # ("🗍", "A paperclip."),
    # ("🗎", "A rectangular paperclip."),
    # ("🗏", "A round paperclip."),
    # ("🗐", "A triangle paperclip."),
    ("🗑️", "A wastebasket."),
    ("🗒️", "A spiral note pad."),
    ("🗓️", "A spiral calendar."),
    # ("🗔", "A calendar."),
    # ("🗕", "A tear-off calendar."),
    # ("🗖", "A planning board."),
    # ("🗗", "A pushpin."),
    # ("🗘", "A round pushpin."),
    # ("🗙", "A triangle pushpin."),
    # ("🗚", "A tack."),
    # ("🗛", "A round tack."),
    ("🗜️", "A clamp."),
    ("🗝️", "An old key."),
    # ("🗞️", "A rolled-up newspaper."),
    # ("🗟", "A newspaper."),
    # ("🗠", "A paper with pencil."),
    # ("🗡️", "A dagger."),
    # ("🗢", "A long sword."),
    # ("🗣️", "A speaking head."),
    # ("🗤", "A bust in silhouette."),
    # ("🗥", "A silhouette of a person."),
    # ("🗦", "A speak-no-evil monkey."),
    # ("🗧", "A hear-no-evil monkey."),
    # ("🗨️", "A speech balloon."),
    # ("🗩️", "A right speech bubble."),
    # ("🗪️", "A left speech bubble."),
    # ("🗫", "A thinking face."),
    # ("🗬", "A zipper-mouth face."),
    # ("🗭", "A face with no good gesture."),
    # ("🗮", "A face with ok gesture."),
    # ("🗯️", "A white angry face."),
    # ("🗰", "A hushed face."),
    # ("🗱", "A frowning face."),
    # ("🗲", "A slightly frowning face."),
    ("🗳️", "A ballot box."),
    # ("🗴", "A mailbox."),
    # ("🗵", "A closed mailbox."),
    # ("🗶", "An open mailbox."),
    # ("🗷", "A mailbox with mail."),
    # ("🗸", "A mailbox with no mail."),
    # ("🗹", "A postbox."),
    # ("🗺️", "A world map."),
    ("🗻", "A mountain."),
    ("🗼", "A Tokyo tower."),
    ("🗽", "A Statue of Liberty."),
    # ("🗾", "A map of Japan."),
    ("🗿", "A moyai."),
    # ("😀", "A frowning face with open mouth."),
    # ("😁", "An anguished face."),
    # ("😂", "A crying face."),
    # ("😃", "A persevering face."),
    # ("😄", "A face with look of triumph."),
    # ("😅", "A disappointed face."),
    # ("😆", "A face with medical mask."),
    # ("😇", "A grinning face with smiling eyes."),
    # ("😈", "A face with tears of joy."),
    # ("😉", "A face with rolling eyes."),
    # ("😊", "A face with thermometer."),
    # ("😋", "A face with open mouth."),
    # ("😌", "A nauseated face."),
    # ("😍", "A face sneezing."),
    # ("😎", "A face with cowboy hat."),
    # ("😏", "A clown face."),
    # ("😐", "A face with rolling eyes."),
    # ("😑", "A lying face."),
    # ("😒", "A drooling face."),
    # ("😓", "A face with monocle."),
    # ("😔", "A nerd face."),
    # ("😕", "A confused face."),
    # ("😖", "A worried face."),
    # ("😗", "A slightly smiling face."),
    # ("😘", "A face with hand over mouth."),
    # ("😙", "A shushing face."),
    # ("😚", "A face with raised eyebrow."),
    # ("😛", "A face without mouth."),
    # ("😜", "A neutral face."),
    # ("😝", "A face with open mouth and cold sweat."),
    # ("😞", "A grinning face with smiling eyes."),
    # ("😟", "A face with open mouth."),
    # ("😠", "A grinning face with smiling eyes."),
    # ("😡", "A face with open mouth and closed eyes."),
    # ("😢", "A grinning face."),
    # ("😣", "A crying face."),
    # ("😤", "A face with cold sweat."),
 ]
