

animal_list = [
    ("Elephant", "A giant, gentle creature with big floppy ears and a long nose called a trunk which it uses to pick things up."),
    ("Kangaroo", "A bouncy animal from Australia with a big pouch to carry its baby, called a joey."),
    ("Giraffe", "The tallest animal with a super long neck to reach the treetop leaves."),
    ("Penguin", "A waddling, tuxedo-wearing bird that loves to slide on ice."),
    ("Flamingo", "A pink bird that stands on one leg and loves to dance."),
    ("Hippopotamus", "A big, round animal that spends most of its time in the water and has a giant mouth."),
    ("Narwhal", "A unicorn of the sea with a long, spiral horn."),
    ("Platypus", "A funny-looking creature with a duck's bill, a beaver's tail, and webbed feet."),
    ("Sloth", "A slow-moving animal that hangs upside down in trees and takes long naps."),
    ("Chameleon", "A lizard that can change colors and has swirly eyes."),
    ("Peacock", "A show-off bird with a huge, colorful tail it spreads out like a fan."),
    ("Porcupine", "A spiky creature that shoots out quills when it feels threatened."),
    ("Zebra", "A horse in striped pajamas."),
    ("Octopus", "An eight-armed sea creature that squirts ink and changes colors."),
    ("Meerkat", "A curious animal that stands on its hind legs and looks around like a little guard."),
    ("Walrus", "A big, blubbery sea animal with huge, long teeth called tusks."),
    ("Aardvark", "A digging animal with a long snout and sticky tongue to catch ants."),
    ("Pufferfish", "A fish that blows up like a balloon when it gets scared."),
    ("Toucan", "A bird with a big, colorful beak that loves to eat fruit."),
    ("Ferret", "A playful, slinky-like creature with a love for tunnels."),
    ("Llama", "A fluffy, long-necked animal that sometimes spits when annoyed."),
    ("Tarsier", "A tiny primate with HUGE eyes and fingers, great for clinging onto branches."),
    ("Axolotl", "A smiling water creature with feathery gills on the sides of its head."),
    ("Armadillo", "A critter with a suit of armor, rolling into a ball when scared."),
    ("Proboscis Monkey", "A monkey with a super long, funny nose."),
    ("Mandrill", "A monkey with a bright blue and red face."),
    ("Koala", "A sleepy, cuddly creature that loves to munch on eucalyptus leaves."),
    ("Tapir", "A forest animal with a funny, trunk-like nose."),
    ("Dik-dik", "A tiny antelope with a funny name and big eyes."),
    ("Blobfish", "A squishy, jelly-like fish that looks grumpy."),
    ("Naked Mole Rat", "A hairless, wrinkly rodent that lives underground."),
    ("Hedgehog", "A small, round animal covered in spiky quills."),
    ("Ostrich", "A big bird that runs really fast but can't fly."),
    ("Panda", "A chubby, black and white bear that munches on bamboo all day."),
    ("Lemur", "A playful primate with big, round eyes and a striped tail."),
    ("Star-nosed Mole", "A mole with a weird, star-shaped nose.")
]


trick_list = [
    "Making a coin 'disappear' behind their ear, only to magically bring it back.",
    "The classic trick of pulling a colorful handkerchief out of an empty bag.",
    "Pouring water into a cup, turning it upside down, and the water being mysteriously gone.",
    "Cutting a piece of rope in half and magically restoring it to its original length.",
    "Turning a plain piece of paper into a colorful picture with just a wave of a wand.",
    "Making a toy levitate in the air with the 'power' of a magic word.",
    "Changing the color of a liquid in a transparent glass just by shaking it.",
    "Creating shadows on a wall that look like animals using only hands and a flashlight.",
    "Guessing the number a child is thinking of between 1 and 10 with a mysterious crystal ball.",
    "Transforming a rubber ball into a square cube with a snap of the fingers.",
    "Floating a paper clip on the surface of water using only the power of surface tension.",
    "Showing how mixing two different colors of clay can create a totally new color.",
    "Bending a straight pencil without breaking it, using the refraction in a glass of water.",
    "Drawing a picture that looks different when viewed from another angle using optical illusions.",
    "Making a 'teleporting' coin move from one hand to another without passing it.",
    "Creating a mini volcano eruption using baking soda and vinegar.",
    "Revealing hidden messages written in invisible ink using the heat from a light bulb.",
    "Growing a 'magic' crystal overnight from a simple solution of salt and water.",
    "Floating a ping pong ball in the air using the power of a hair dryer.",
    "Building a paper airplane that can loop-the-loop with a special fold technique.",
    "Mixing oil and water in a bottle and watching them magically separate.",
    "Creating musical notes using different levels of water in glass bottles and tapping them.",
    "Balancing a coin on the edge of a dollar bill without it falling.",
    "Making a balloon stick to the wall using static electricity after rubbing it on hair.",
    "Transforming a square piece of paper into a beautiful origami animal.",
    "Solving a puzzle cube in seconds after mixing it up, showcasing the art of algorithms.",
    "Turning milk into a solid form using simple household ingredients.",
    "Showing how a prism can split a ray of light into a beautiful spectrum of colors.",
    "Demonstrating how a magnet can push and pull objects without touching them.",
    "Creating a rainbow in a glass of water using just a flashlight.",
    "Building a bridge using only paper and tape that can hold a toy car.",
    "Changing the pitch of a voice using a balloon filled with different gases like helium.",
    "Generating electricity by rubbing a balloon on hair and making a small light bulb glow.",
    "Using simple household items to create a whirlpool in a bottle."
]

prank_list = [
    "Place a small piece of clear tape over the bottom of a computer mouse so it doesn't work.",
    "Switch around the order of shoes in the closet for a moment of confusion.",
    "Put a toy spider under someone's pillow and watch their reaction when they lift it up.",
    "Offer to serve a drink and give them a cup filled with water containing a plastic ice cube with a fake bug inside.",
    "Attach a long piece of clear thread to a toy and move it from a distance, making it look like it's moving on its own.",
    "Place a whoopee cushion on someone's chair just before they sit down.",
    "Swap the cereal bags inside their boxes, so when someone pours out their morning cereal, they get a surprise.",
    "Tightly twist a rubber band around the handle of the sink's sprayer, so it sprays water when turned on.",
    "Switch the salt and sugar containers, so morning coffee gets a salty twist.",
    "Leave a note under someone's pillow saying 'You're being watched' and watch them look around the room.",
    "Stick googly eyes on all the items in the fridge so they 'stare' when the door is opened.",
    "Replace the contents of an Oreo cookie with toothpaste and offer it as a treat.",
    "Add food coloring to a jug of milk for a colorful breakfast surprise.",
    "Turn all the framed photos or artworks in the house upside-down.",
    "Put a small toy or item inside someone's shoe for a foot-tickling surprise.",
    "Inflate a balloon and hide it behind a door, so it pops out when someone opens the door.",
    "Stick a balloon to the tailpipe of a car (only with adult supervision and ensuring no damage).",
    "Place clear plastic wrap across a doorway at chest height for a surprise walk-through.",
    "Quietly play a recording of a strange noise and hide the source, watching the bemused reactions.",
    "Use a harmless, washable marker to draw a tiny smiley face on the back of someone's hand while they sleep.",
    "Create a fake remote by wrapping a block of wood in paper and hand it over when someone wants to change the TV channel.",
    "Place a stuffed toy on someone's bed, pretending it's 'resting' and needs not to be disturbed.",
    "Hide a small alarm clock in the room, set to go off at an unexpected time.",
    "Replace someone's bookmark with a silly note or picture.",
    "Put tiny stickers on the bottom of someone's slippers or shoes so they leave funny footprints.",
    "Carefully remove the filling from a pillow and replace it with inflated balloons.",
    "Stick a funny note on the back of someone's shirt without them noticing.",
    "Leave a trail of toy footprints leading to a hidden 'treasure' or surprise.",
    "Attach a helium-filled balloon to someone's bed, so it floats up when they pull back the covers.",
    "Fill an empty sunscreen bottle with vanilla yogurt and pretend to eat it.",
    "Tell someone there's an 'invisible' pet (like a unicorn) in the garden and have them search for it.",
    "Replace the batteries in a toy with empty ones and act surprised when it doesn't work.",
    "Offer a hand (fake toy one, of course) when someone asks for 'a hand' with something.",
    "Hide a tiny toy under a cup, shuffle the cups around, and have someone guess where it's hiding.",
    "Put jelly in a drinking straw, let it set, and then offer the straw with a drink.",
    "Carefully put a small amount of washable paint on the soap bar, so it colors hands when used."
]


profession_list = [
    "Astronaut",
    "Doctor",
    "Firefighter",
    "Teacher",
    "Veterinarian",
    "Police Officer",
    "Chef",
    "Dentist",
    "Farmer",
    "Pilot",
    "Dancer",
    "Zookeeper",
    "Engineer",
    "Nurse",
    "Scientist",
    "Mail Carrier",
    "Bus Driver",
    "Soldier",
    "Musician",
    "Librarian",
    "Baker",
    "Athlete",
    "Artist",
    "Actor",
    "Magician",
    "Construction Worker",
    "Hairdresser",
    "Photographer",
    "Marine Biologist",
    "Journalist",
    "Mechanic",
    "Astronomer",
    "Architect",
    "Fashion Designer",
    "Fisherman",
    "Plumber"
]

# things with distinctive sounds that children will recognize
soundy_things_list = [
    "Toy train",
    "Bicycle bell",
    "Squeaky toy",
    "School bus brakes",
    "Jump rope hitting the ground",
    "Crayons or colored pencils on paper",
    "Electronic handheld game sounds",
    "Lunchbox latch snapping",
    "Popping bubble wrap",
    "Watercolor paintbrush swishing in a cup",
    "Slinky going down stairs",
    "Toy cash register",
    "Building blocks tumbling",
    "Pencil sharpener",
    "Rubber ball bouncing",
    "Plastic action figure articulations",
    "Flipping storybook pages",
    "Push-toy with popping balls",
    "Toy phone ringing",
    "Sand toys digging in the sandbox",
    "Piano or keyboard toy",
    "Toy drum",
    "Zipper of a backpack",
    "Velcro shoe straps",
    "Wind-up toy moving",
    "Jack-in-the-box popping",
    "Chalk drawing on sidewalk",
    "Toy car engine",
    "Whistle",
    "Blowing bubbles wand",
    "Toy kitchen appliances",
    "Electronic toy animal sounds",
    "Yoyo going up and down",
    "Water gun squirting",
    "Popping balloons",
    "Children's music box playing"
]


home_item_list = [
    ("Squeaky toy", "A colorful toy that squeals like a mischievous mouse when you squeeze it!"),
    ("Rubber duck", "A sunny yellow duck that loves to float in the bathtub, sometimes wearing sunglasses!"),
    ("Slime", "A gooey, stretchy blob that feels like alien boogers!"),
    ("Kaleidoscope", "A magical telescope that shows a festival of dancing colors and shapes!"),
    ("Cuckoo clock", "A quirky wooden clock with a bird that pops out to announce the time with a 'cuckoo'!"),
    ("Whoopie cushion", "A sneaky pillow that lets out a hilarious fart sound when someone sits on it!"),
    ("Magic 8-ball", "A mystical black ball that answers your yes-or-no questions with cryptic messages!"),
    ("Slinky", "A metal or plastic spring that tiptoes down stairs like a wobbly robot!"),
    ("Bubble wrap", "A sheet of popping joy that makes a tiny 'pop' sound when you press the bubbles!"),
    ("Wind-up toy", "A little toy that scuttles across the floor with jerky movements when wound up!"),
    ("Jellybean jar", "A transparent jar filled with rainbow-colored candies, each with a surprise flavor!"),
    ("Magnet", "A magical piece that pulls metal things towards it as if whispering secrets!"),
    ("Snow globe", "A miniature winter wonderland trapped inside a crystal ball!"),
    ("Music box", "A tiny box that plays enchanting melodies when opened, like fairy whispers!"),
    ("Bouncy ball", "A rubbery ball that springs back with joy every time you throw it down!"),
    ("Balancing bird", "A mysterious bird toy that can balance on its beak without falling over!"),
    ("Glow sticks", "A stick that lights up in neon colors, turning any room into a disco party!"),
    ("Whoopee whistle", "A tiny instrument that makes a hilarious 'whoo' sound when you blow into it!"),
    ("Sticky hand", "A stretchy, colorful hand that sticks to walls and snatches things like a mischievous ghost!"),
    ("Pinwheel", "A spinning wheel of colors that dances in the breeze like a daydream!"),
    ("Play-dough", "A moldable, colorful dough that you can shape into anything from monsters to cupcakes!"),
    ("Finger puppet", "A tiny creature that comes to life when you slide it onto your finger!"),
    ("Yoyo", "A spinning toy on a string that goes up and down, like a mini circus act!"),
    ("Fake spider", "A creepy-crawly plastic critter that can give anyone a silly scare!"),
    ("Jack-in-the-box", "A box with a surprise jester inside that pops out to the tune of a song!"),
    ("Magic wand", "A sparkly stick that can turn anyone into a frog – or maybe just make them giggle!"),
    ("Flarp noise putty", "A squishy putty that makes the funniest, tootiest sounds when you press it!"),
    ("Kazoo", "A small musical device that buzzes like a bumblebee when you hum into it!"),
    ("Disappearing ink", "A mischievous liquid that looks like ink but vanishes into thin air!"),
    ("Toy binoculars", "A pair of mini glasses that make far away things look like they're right in front of you!"),
    ("Prism", "A crystal that splits sunlight into a rainbow, as if it's holding a piece of magic!"),
    ("Feather", "A soft, tickly thing that once belonged to a bird and can make you giggle when brushed against your skin!"),
    ("Harmonica", "A pocket-sized instrument that wails like a train when you blow into it!"),
    ("Gag glasses", "Giant spectacles with a fake nose and mustache attached, turning you into a comical detective!"),
    ("Toy parachute", "A tiny person with a parachute that glides down gracefully when thrown in the air!"),
    ("Echo microphone", "A mic that repeats everything you say in a funny, echoey voice!")
]

relation_list = [
    "Mrs. Miller, the kind-hearted kindergarten teacher with silver curls and glasses that always seem to slide down her nose, who always has a story or song up her sleeve.",
    "Grandpa Joe, with his deep laughter lines and stories of 'the good old days', often seen with a fishing rod or a wooden toy he crafted in his shed.",
    "Buddy, the family's golden retriever, always wagging his tail, his fur as soft as cotton, and always ready to play fetch or be a comforting presence.",
    "Ms. Karen, the school librarian with her owl-like glasses, a passion for fairy tales and an uncanny ability to recommend the perfect book.",
    "Mr. Roberts, the friendly neighbor with a garden full of sunflowers, who hands out homemade cookies every Saturday and knows all the local bird songs.",
    "Aunt Clara, with her collection of colorful scarves and jingling bracelets, who tells tales of her travels and teaches dances from all over the world.",
    "Tommy, the same-aged friend from next door, with boundless energy, a collection of action figures, and always an idea for a new adventure game.",
    "Miss Gina, the ballet instructor in her elegant tutu, who moves with grace and teaches the art of dance with patience and enthusiasm.",
    "Mr. Green, the school bus driver with a cap always askew, a jolly demeanor, and a warm greeting for every child as they step onto his bus.",
    "Mom, with her comforting scent and warm hugs, who reads bedtime stories, makes the best sandwiches, and knows just how to soothe a bad day away.",
    "Dad, with his strong hands and reassuring voice, who builds forts out of blankets, teaches how to ride a bike, and tells jokes that make everyone groan.",
    "Fluffy, the family cat, with sleek black fur and a regal demeanor, often found sunning by the window or playfully chasing a toy mouse.",
    "Coach Mike, the enthusiastic soccer coach with a whistle around his neck, always encouraging, teaching teamwork and the joys of running in an open field.",
    "Ms. Lila, the art teacher with paint on her apron and a twinkle in her eye, introducing the world of colors, shapes, and the magic of creativity.",
    "Uncle Ben, the one with a penchant for magic tricks and surprise visits, always with a new riddle or a small toy from his many trips.",
    "Sara, the friendly cafeteria lady, with her hair in a net, who serves lunches with a smile and always sneaks in an extra fruit for the favorites.",
    "Mrs. Peters, the school principal with a stern yet kind face, maintaining order in school but also known to join in for a dance or a game occasionally.",
    "Sophie, the older sister by four years, with her collection of dolls, secret diaries, and the ability to both tease and protect fiercely.",
    "Jack, the gentle giant of a janitor at school, with keys jangling from his belt and stories of hidden school treasures, always ready with a helping hand.",
    "Grandma Ana, with her old-world tales, scents of freshly baked bread, a comforting lap, and soft lullabies sung in a language of old.",
    "Penny, the little friend from ballet class with a penchant for pink, twirling together and sharing dreams of becoming famous dancers.",
    "Dr. Smith, the pediatrician with a friendly demeanor, a drawer full of stickers, and the ability to make check-ups less scary and more fun.",
    "Mr. Grey, the postman with a bag full of letters, a cheerful whistle, and news of the outside world, sometimes bringing packages with surprises inside.",
    "Lily, the cousin from out of town, always with a new board game to share, endless tales of her city life, and a matching sense of mischief.",
    "Mr. Hudson, the elderly man at the park feeding pigeons, with tales of wars and old city tales, sharing wisdom and occasionally a candy.",
    "Mrs. Chang, the music teacher, with her piano tunes and encouraging nods, teaching the joys of rhythms, beats, and the first notes on a recorder.",
    "Charlie, the ice cream vendor with his jingling truck, known routes, and the magical ability to appear just when a summer day gets too hot.",
    "Aunt Mia, the scientist with a lab coat, who sends postcards of animals, rocks, and stars, sparking curiosity about the world and how it works.",
    "Sammy, the class clown, with wild hair and a wilder sense of humor, always with a joke, a prank, or a funny face up his sleeve.",
    "Mrs. Johnson, the school counselor with a room full of toys and books, always ready to listen, comfort, and guide through the maze of feelings.",
    "Max, the kid with a wheelchair and a radiant smile, teaching lessons of resilience, joy, and that differences make us unique and special.",
    "Miss Ellie, the young woman at the local bookstore, with recommendations for young readers and tales of far-off worlds and adventurous quests.",
    "Mama Rosa, the lady at the community church, always with a kind word, a story from the Bible, and a loving embrace for every child.",
    "Bobby, the older brother's friend, with his video games, cool gadgets, and the aura of 'grown-up' mystery, occasionally letting the little one join in their games."
]
